### ISSUE TITLE
How to get cell ids for an area of amplification?

### ISSUE THREAD

**Issue by s2hui** [broadinstitute/infercnv#158]
Hello,
I have generated a heatmap using inferCNV and wanted to fetch the cell ids corresponding to an area of amplification.  
In the following cutout [image](https://drive.google.com/file/d/1RDM953WhcnfhtrXMkH845rpG0Af1qBrw/view?usp=sharing), I am interested in getting the subset of cell ids or indices within the red/pink cluster (defined by the green box) that correspond to the red area on the heatmap (defined by the red box).
I looked within the infercnv_obj but couldn't find this information.
Thanks for your help,
shui

**Comment by GeorgescuC** [comment]
Hi @s2hui ,

The group of cells you selected looks like it is an entire (top level) branch in the dendrogram of the red/pink cluster. In this case, the easiest is to use the ".observations_dendrogram.txt" output file matching the heatmap file name. It contains the dendrograms of all the clusters defined by the annotation (since you have grouped by annotation) as newick strings (1 newick string per line). With regards to the order in the legend, the cells and clusters in the heatmap are ordered from bottom to top, so the first newick dendrogram will be the one of the cluster at the bottom of the figure.
Once you have selected the newick string for the red/pink cluster, you can select the cell names from the smaller of the 2 top level branches to match your selection. (There are online tools if you do not have anything to parse the newick tree already available, such as http://etetoolkit.org/treeview/ )

Regards,
Christophe.

**Comment by s2hui** [comment]
Hello,

1) Is the corresponding dendrogram file infercnv.observations_dendrogram.txt for the final heatmap?  

2) Is the file infercnv.observations_groupings.txt supposed to contain the leaves of the dendrogram in the final heatmap?  I confirmed that the cluster of interest (red/pink) corresponds to Cluster 3 in this file by looking up the hex colour in this file.  However when I try to search for the barcodes in this cluster in the dendrogram file I can't find any.

3) You wrote "It contains the dendrograms of all the clusters defined by the annotation (since you have grouped by annotation) as newick strings (1 newick string per line)."  Are you saying that there should be one newick string per line corresponding to one cluster (i.e. if I have 8 clusters I should have 8 newick strings, one per line)?  My file infercnv.observations_dendrogram.txt only has one newick string (the barcodes seem to all correspond to cluster 1) meanwhile I have 8 clusters.  

Thanks again for your help,
shui

**Comment by GeorgescuC** [comment]
Hi @s2hui ,

Yes, the infercnv.observations_dendrogram.txt is the file matching the final heatmap.

About the missing barcodes/newick strings, that is my mistake. I fixed the problem on the master/devel branch but forgot to apply the fix to the current release on BioConductor. I now did and the new version 1.0.3 will be available for BioConductor 3.9 when their next build is done (daily build that takes a full day to fully complete). If you want to update right away, you can install directly from github using devtools: `devtools::install_github("broadinstitute/infercnv", ref="RELEASE_3_9")`. 

Once you have the new version installed, you can either simply rerun the same command that you did before, which will reload the backed up objects and then redo the plotting, or you can manually load (`readRDS()`) a saved infercnv object and use `plot_cnv()` with options matching the ones you used in `run()`.

Regards,
Christophe.

**Comment by s2hui** [comment]
Thanks, it works.
shirley

**Comment by aleshchyk** [comment]
Hello,

I have a similar issue. I would like to extract the row labels (cell barcodes) from the final InferCNV heatmap, but I can't find  infercnv.observations_dendrogram.txt in my output dir (it was generated in 3/2019). Instead, I have infercnv.preliminary.observation_groupings.txt. Is this the file I need to use?
Thank you.
