### ISSUE TITLE
Error in add_to_seurat

### ISSUE THREAD

**Issue by pangxueyu233** [broadinstitute/infercnv#160]
Hello,
Recently,  I want to integrated the output of inferCNV into seurat object by infercnv 1.1.2. but there is showing an error as following:
Error in `*tmp*`[[c]] :
  attempt to select less than one element in integerOneIndex
Can you help me work it out? 

Thanks a lot.

**Comment by GeorgescuC** [comment]
Hi @pangxueyu233 ,

Could you run please this line `options(error = function() traceback(2))` and then try to run the add_to_seurat method again please? It should display a longer error message that will give me more information on where the issues happens.

Regards,
Christophe.

**Comment by pangxueyu233** [comment]
Hello, @GeorgescuC 
This is my error info:

INFO [2019-07-16 13:07:54] No Seurat object provided, will only write metadata matrix.
Error in `*tmp*`[[c]] :
  attempt to select less than one element in integerOneIndex
3: (function ()
   traceback(2))()
2: .get_features(infercnv_obj = infercnv_obj, regions = regions,
       hmm_genes = hmm_genes, center_state = center_state, scaling_factor = scaling_factor,
       top_n = top_n)
1: add_to_seurat(seurat_obj = NULL, "/mnt/data/user_data/xiangyu/workshop/scRNA/eso_scRNA/CNV/inferCNV/all_patients_compared/Heso5/",
       top_n = 1e+06)

thanks a lot

**Comment by pangxueyu233** [comment]
> Hello, @GeorgescuC
> This is my error info:
> 
> INFO [2019-07-16 13:07:54] No Seurat object provided, will only write metadata matrix.
> Error in `*tmp*`[[c]] :
> attempt to select less than one element in integerOneIndex
> 3: (function ()
> traceback(2))()
> 2: .get_features(infercnv_obj = infercnv_obj, regions = regions,
> hmm_genes = hmm_genes, center_state = center_state, scaling_factor = scaling_factor,
> top_n = top_n)
> 1: add_to_seurat(seurat_obj = NULL, "/mnt/data/user_data/xiangyu/workshop/scRNA/eso_scRNA/CNV/inferCNV/all_patients_compared/Heso5/",
> top_n = 1e+06)
> 
> thanks a lot

**Comment by GeorgescuC** [comment]
Hi @pangxueyu233 , 

Would you be able/willing to share the infercnv object you are using when getting this error so I can debug the issue? (I will keep it private)

Regards,
Christophe.

**Comment by nyuhuyang** [comment]
Hi @GeorgescuC,

I have the same bug. It happens when the function `.get_features` tries to copy the top_n_loss and top_n_duplic information into all_features.
` clust = subclust_name_to_clust[[subclust_name]][1]`
`subclust = subclust_name_to_clust[[subclust_name]][2]`
`all_features[[feature_name]]
[names(infercnv_obj@tumor_subclusters$subclusters[[clust]][[subclust]])] = TRUE`
It happens when there is no `subclust_name` exist in `names(subclust_name_to_clust)`, so end up with  `clust = NULL` and `subclust = NULL` and it generates error:
`Error in infercnv_obj@tumor_subclusters$subclusters[[clust]] : 
  attempt to select less than one element in get1index`

In my case, I do have subcluster CNV loss based on heatmap. `sample1.sample2_s1` in `top_n_loss[[i]]$subclust_name`, and `sample1.sample2.1.1.1.1` in `names(subclust_name_to_clust)`. I guess this error might be due to subluster label mismatch.

I can share my infercnv object with you.

**Comment by GeorgescuC** [comment]
Hi @nyuhuyang ,

That would be very helpful so I can debug it! The files I need are `run.final.infercnv_obj`, `HMM_CNV_predictions.HMMi6.*.Pnorm_0.[0-9]+.pred_cnv_regions.dat` and `HMM_CNV_predictions.HMMi6.*.Pnorm_0.[0-9]+.pred_cnv_genes.dat`. You can send them at 
cgeorges `at` broadinstitute `dot` org.

Could you also tell me what options you used to generate this object/for this run?

Regards,
Christophe.

**Comment by GeorgescuC** [comment]
Hi @nyuhuyang ,

Thank you for sending me the files. I was able to figure out the issue, which was basically due to having output files from runs with anaylsis_mode="samples" and analysis_mode="subclusters" in the same output folder. No difference was made when trying to load the files in add_to_seurat, so it would load the first in alphabetical order, "samples", while loading the run.final.infercnv_obj that had subclustering information from the "subclusters" run. Because both analysis_mode produce different cluster names, there would be a mismatch when trying to map the CNVs found in the .dat files to the cells and subclusters information stored in the infercnv_obj.

The issue should now be fixed (with a couple other related fixes) on the master branch, and automatically identify which analysis_mode was used in the infercnv_obj loaded to read the matching .dat files (that now all have unique names based on the analysis_mode). You will however need to rerun infercnv in a clean folder for the object contents and output files to be correct.
This should also fix the issue @pangxueyu233 had.

Regards,
Christophe.

**Comment by deeKal** [comment]
I was getting the same error after running infercnv with a lower leiden resolution (lower res = fewer clusters). I was able to fix it by removing all the files that were generated on the first run (for example, the General_HCL_all_observations_s*_members.txt for the clusters that were called in the run with the higher resolution - but only these, any redundant file). Just mentioning it in case anyone else stumbles across this error.
