### ISSUE TITLE
infercnv.observations_dendrogram.txt does not include all tumor cells

### ISSUE THREAD

**Issue by ncasiraghi** [broadinstitute/infercnv#163]
Hi! great and extremely useful tool.
My sample consists of 3 different tumor and 1 normal cell populations, as properly indicated in the cellAnnotations file.
The InferCNV workflow completes without any error messages and the `infercnv.png` output correctly shows all the cell populations. However, when I inspect the `infercnv.observations_dendrogram.txt` there are barcodes only for one tumor population. 
thanks in advance for any help!

**Comment by GeorgescuC** [comment]
Hi @ncasiraghi , 

This issue should be fixed in version 1.0.3 of the BioConductor 3.9 release, and both the master and RELEASE_3_9 branches on the github if you use those versions, so I would suggest updating your installed version. If you still have the issue with them, please let me know.

Regards,
Christophe.
