### ISSUE TITLE
How many normal cells are required as a reference?

### ISSUE THREAD

**Issue by zezhuo** [broadinstitute/infercnv#188]
Hi infercnv team,

I my data set, macrophages is about 1% of total cells. I wonder will it be enough to served as a reference? What is the minimum percentage for a reference. Thanks!

Regards,
Nelson

**Comment by GeorgescuC** [comment]
Hi @zezhuo ,

There are no precise values for this, but from the different datasets we used, you likely need at least about a 100 cells for reference (so that random noise is not seen as actual signal). However, you may need more than that if you cells have distinct subpopulations/subclones, so that all are properly represented. For this, since infercnv also plots references in the upper part of the figures, you can check whether they look "clean", or if they distinguish in multiple groups with some showing signal. If that is the case, you can try using the "num_ref_groups" option and set it to the number of groups you want to split the hclust of references in.

Regards,
Christophe.

**Comment by zezhuo** [comment]
Hi Christophe,

Thanks for the patient explanation.

Regards,
Nelson
