### ISSUE TITLE
Error in Step 7

### ISSUE THREAD

**Issue by angelussong** [broadinstitute/infercnv#189]
Hi, 

Sorry to bug you with this. I'm working on a single-cell RNA-seq project trying to identify tumor cells within tumor and biopsy samples. Previously, I've used some known markers to identify a subset of luminal epithelial cells as "tumor" and others as "benign". 

I would like to use infercnv to make a CNV estimation to validate my clustering. I followed the instructions and created an infercnvobject. 
I tried to run this line: 
infercnv_obj = infercnv::run(infercnv_obj,min_cells_per_gene = 1,window_length = 101,
                             cutoff=0.1, 
                             out_dir=CNV_infer_OUTDIR,
                             cluster_by_groups=T,
                             denoise=TRUE,
                             plot_steps=T,
                             HMM=T)

I got this error during STEP 4 and here is the complete log: 
STEP 1: incoming data

INFO [2019-11-04 17:10:37] 

	STEP 02: Removing lowly expressed genes

INFO [2019-11-04 17:10:37] ::above_min_mean_expr_cutoff:Start
INFO [2019-11-04 17:10:37] Removing 11451 genes from matrix as below mean expr threshold: 0.1
INFO [2019-11-04 17:10:37] validating infercnv_obj
INFO [2019-11-04 17:10:37] There are 7912 genes and 3604 cells remaining in the expr matrix.
INFO [2019-11-04 17:10:38] no genes removed due to min cells/gene filter
INFO [2019-11-04 17:10:46] 

	STEP 03: normalization by sequencing depth

INFO [2019-11-04 17:10:46] normalizing counts matrix by depth
INFO [2019-11-04 17:10:47] Computed total sum normalization factor as median libsize: 2927.000000
INFO [2019-11-04 17:10:55] 

	STEP 04: log transformation of data

INFO [2019-11-04 17:10:55] transforming log2xplus1()
INFO [2019-11-04 17:11:03] ::plot_cnv:Start
INFO [2019-11-04 17:11:03] ::plot_cnv:Current data dimensions (r,c)=7912,3604 Total=7079180.45436521 Min=0 Max=10.4730364787086.
INFO [2019-11-04 17:11:03] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2019-11-04 17:11:19] plot_cnv(): auto thresholding at: (-1.893599 , 2.390125)
INFO [2019-11-04 17:11:20] plot_cnv_observation:Start
INFO [2019-11-04 17:11:20] Observation data size: Cells= 0 Genes= 7912
INFO [2019-11-04 17:11:20] clustering observations via method: ward.D
Error in seq_len(max(obs_annotations_groups)) : 
  argument must be coercible to non-negative integer
 
This is quite confusing to me as it showed "Cells=0". 
I'm wondering what could be the cause of the problem? Is it because the auto threshold is too narrow but all my cells are beyond that so no cells would be left? How could I set the threshold then? 

Thanks very much, 

Hanbing Song

**Comment by GeorgescuC** [comment]
Hi @angelussong ,

Could you please also send the command you used to create the initial infercnv object as well as your infercnv version number? If neither of the things below work, could you also send a couple lines from your annotation file?

From the message you sent before editing, a potential issue are the dots in the annotation names. I would try replacing them with another character such as - or _ to see if it helps. With your current error however, do you maybe have all your cells set as references?

Regards,
Christophe.

**Comment by angelussong** [comment]
Hi Christophe, 

Thanks for your reply! Yes, this is the command I used to create the infercnv: 
infercnv_obj=CreateInfercnvObject(raw_counts_matrix = LE_raw,annotations_file = "Tumor_annotation.txt",gene_order_file =DF,delim = "\t",ref_group_names=c("Benign","Tumor"))

DF is the dataframe I generated for the gene position. 

Yes, the annotation file contains all the cell names and the group annotation according to my previous analysis. Do you mean I should have perhaps only a proportion as a reference (the annotation file should only contain a subset of cells)?

Thanks, 

Hanbing Song

**Comment by angelussong** [comment]
And here are some lines from my annotation file: 
V1	V2
GGCAATTGGGAC	Benign
GACGGCATGACA	Benign
GTAAACTCGGCC	Tumor
GTCCCTAAGACC	Tumor
GCCCAGCCACCT	Benign

**Comment by GeorgescuC** [comment]
Hi @angelussong ,

By specifying `ref_group_names=c("Benign","Tumor")` when you created the infercnv object, all the cells in your dataset are used as references, so there are no cells left as observations, hence nothing to plot on the lower part of the figure. Based on the names of your annotations, you should set this option to `ref_group_names=c("Tumor")` and then `run()` infercnv as before.

Regards,
Christophe.

**Comment by angelussong** [comment]
Thank you so much Christophe! I am able to get it to run now. 

However, I do have another question now. I tried setting ref_group_names=NULL and then managed to run the infercnv without any problems. This time, I have three categories. And based on our hypothesis we would see the two sets of tumor cells exhibit CNV variants and all normal cells would have little to no CNV variants. 

I turned on the plot_steps so that I could save all the intermediate results. According to this figure: infercnv.14_HMM_predHMMi6.hmm_mode-samples.Pnorm_0.5.repr_intensities, I see that the two groups of interest indeed showed some variants in the copy number and nothing in the benign group. 
![image](https://user-images.githubusercontent.com/40570906/68695519-0d6c6c80-0530-11ea-8adb-66fe5d4f75d5.png)

But this difference seemed to have disappeared in the final infercnv.png. I do see a lot of noise in the figure. 
![image](https://user-images.githubusercontent.com/40570906/68695553-1e1ce280-0530-11ea-8031-d6913562611c.png)

I'm wondering why that is and if there is any way to somehow denoise it even more. Or am I reading the figures wrong? 


Thanks so much! 

Hanbing Song

**Comment by GeorgescuC** [comment]
Hi @angelussong ,

Based on the final plot, it looks as if no smoothing was done, or with a very small window size. Did you change the options used in `run()` compared to your first message?
With how the current residual expression figure looks (final infercnv.png), I would not use the results from the HMM predictions as there seems to be an upstream issue in processing the data.

If you did not change the options used, could you please send the plots from the different steps so I can try to identify where the issue occurs?

Regards,
Christophe.

**Comment by angelussong** [comment]
Hi Christophe, 

Thanks for the quick reply. I changed the window_length to 50 compared to the default 100. And I used 0.01 as the cutoff since if the 0.1 threshold only left me with <8000 genes. I'm wondering how that would affect the smoothing process? 

I'll test the reference as you instructed above and restored the window size to 100 to test how the results change. I identified the tumor cells based on quite distinctive expression patterns so I would assume the estimated CNV would show some differences. Or are there any factors that I should take into consideration before running inferCNV? 

Thanks, 

Hanbing Song

**Comment by GeorgescuC** [comment]
Hi @angelussong ,

What type of sequencing data is this? How many genes are kept with the 0.01 threshold? Maybe keeping a lot more genes (could maybe be even more inflated by min_cells_per_gene=1) while at the same time reducing the window size made the smoothing barely effective because most values are zeros.

In the case you know a certain group of cells is non tumor cells, you can set them as the reference annotation group(s), that way the results will be easier to interpret as any CNV pattern will be relative to that reference level of expression, and not the average of all your cells.

Regards,
Christophe.

**Comment by angelussong** [comment]
This is a Seqwell single-cell RNA-seq dataset. And 15000 genes were kept within the 0.01 threshold. Yes, your suggestion makes a lot of sense. I'll use the benign or normal cells as a reference in the hope of seeing some distinctive patterns. 

Thanks!

**Comment by angelussong** [comment]
Hi Christophe, 

I've managed to have some results from infercnv on my dataset. But so far it's been difficult to isolate clusters of cells from the CNV estimation. 

I've used a set of immune cells (which I know are not tumor cells) as reference to have some idea of what the CNV profiles tumor cells would have. I'm wondering if this analysis would be better if I use the same type of cells (normal luminal cells vs tumor luminal cells). Another question of mine is that how could I separate cells from the same cluster in the infercnv result? 

Thanks! 

Hanbing Song

**Comment by GeorgescuC** [comment]
Hi @angelussong ,

Using the same type of cells in the reference and observations is the ideal way to run infercnv as it allows to highlight signal specific to the tumor related changes, and not cell type specific variation. If you do not have the same cell type, you can use another one as a proxy, but some of the signal may actually be cell type variation amplified by noise. Overall, thanks to the smoothing step, changes in the expression of a single gene (whether it is tumor-related, cell type specific or noise) will not affect CNV results by much, but changes in the expression level of multiple gene in proximity will. Comparing cell types that express a larger number of non overlapping genes could also lead to reduced effectiveness of the smoothing because of the increased number of 0s in the matrix, but this will vary from case to case.

With regards to separating cells from the same cluster, do you mean a user defined cluster from the input annotation, or a cluster defined by the infercnv algorithm? If you mean user defined clusters, you can try using the option `analysis_mode="subclusters"` to let inferCNV try to identify the different subclusters present. If you mean to further separate clusters defined by infercnv in this way, all infercnv plotting also generates by default a text output with the dendrograms displayed on the side of the figure that reads from bottom to top.

Regards,
Christophe.

**Comment by angelussong** [comment]
Thank you so much for the detailed explanation! It's super helpful for our project!
