### ISSUE TITLE
Select k when No reference cells available + automate process

### ISSUE THREAD

**Issue by namit-k** [broadinstitute/infercnv#194]
Hi,
I am working with HNSCC dataset - GSE103322, Cell, 2017.
The objective is to optimize the workflow for 'identifying tumor cells' when NO reference is available. I am able to process the files keeping ref_group_names=NULL and by specifying the k_obs_groups. 

Questions: 
1) For identifying the tumor cells, I am manually identifying the tumor cell cluster looking at the "infercnv.png" file. 
- 	Is there a way to automate this process? 
- 	Are the values saved in any file where a threshold can be applied to identify tumor cells?

2) How to identify the appropriate 'k value' to use? 
Depending on if k= 2 or 6, the results do vary. Do you have any recommendations? 
When k=2, there is a large cluster for normal cells in which some cells still have CNV.

Code below:
"annots" file lists each cell as normal:
HN26_P14_D11_S239_comb        normal
HN26_P14_H05_S281_comb        normal

infercnv_obj = CreateInfercnvObject(raw_counts_matrix=as.matrix(exp.gse103322), annotations_file="annots.txt", delim="\t", gene_order_file="gencode_v19_gene_pos.txt",  ref_group_names=NULL)

infercnv_obj = infercnv::run(infercnv_obj, cutoff=1, out_dir= outpath, cluster_by_groups=F, 
plot_steps=F, HMM=F, denoise=T, k_obs_groups = k, num_threads = 12)

**Comment by GeorgescuC** [comment]
Hi @namit-k ,

> Are the values saved in any file where a threshold can be applied to identify tumor cells?

Yes, every time a plot is generated, you will find a file with the same name and ending in ".observations.txt" that contains the full matrix displayed in the heatmap. You can also use `readRDS()` to load a backup of the infercnv_obj at a given step and access the values in the `@expr.data` slot.

> How to identify the appropriate 'k value' to use? Depending on if k= 2 or 6, the results do vary. Do you have any recommendations?

You can try using the `analysis_mode="subclusters"` option in `infercnv::run()` so that infercnv tries to generate as many clusters as needed (and not too many).

> For identifying the tumor cells, I am manually identifying the tumor cell cluster looking at the "infercnv.png" file.
Is there a way to automate this process?

You could use some rules to do that, but you would have to be very careful in some cases. The issue when not providing a reference is that the signal you see could be the inverse of the actual signal if there are more tumor cells than reference cells in your dataset. Or if all your cells are tumor cells with a common CNV, it would look as if all cells are normal in that region. If 50% of your cells are normal and 50% have a common CNV (for example a loss), all cells would look as if they had a half intensity CNV in that region (as normals would have 4/3 the expression of the average and tumors would have 2/3).
infercnv can help you define clusters of cells and subclones within a population, but for assigning the normal or tumor label on those clusters, I would suggest using it in combination with other methods.

Regards,
Christophe.

**Comment by namit-k** [comment]
Hi @GeorgescuC
Thanks for your suggestions. 

Looking at the examples shared in wiki documentation - annots files already has the malignant/normal classification. But when you are running infercnv on these samples for the first time, how are you obtaining this malignant/normal classification info? 
I am presuming classification info is obtained from other sources and already available?  

I tried running infercnv with analysis_mode="subclusters" and keeping k= default. 
infercnv_obj = infercnv::run(infercnv_obj,cutoff=1, out_dir= outpath ,plot_steps=F,HMM=F, denoise=T,cluster_by_groups=F, analysis_mode="subclusters",num_threads = 28)

Output has only one dendrogram group (no sub clustering) and it is not clear how to identify barcodes of cells exhibiting cnv, any suggestions?   

![image](https://user-images.githubusercontent.com/28112690/69379231-11119900-0c7e-11ea-8153-7334ff7297af.png)

Thanks,
Namit

**Comment by GeorgescuC** [comment]
Hi @namit-k ,

Infercnv allows you to identify different subpopulations based on their CNV profiles, but it can not be used to give an assignment about which are the normal ones if you do not have any prior knowledge of what some normal cells look like as everything is relative to the reference (or all observations when there are no references).

For the subclustering, it was actually run, but there is no obvious split in the dendrogram or column coloring (left side) that comes with it alone. The main use of subclustering is for better HMM predictions, as each subcluster gets separate predictions. If you want to see splits on the figure, you can set k_obs_groups to a different value (as the default is 1).
If you want to get the cells IDs for each subcluster, you can reload the final infercnv object and read the infercnv_obj@tumor_subclusters slot that contains both the hclust object (dendrogram) and the list of cell indices (the list is named by cells).

In addition, if you run the HMM predictions, you can use the add_to_seurat method ( https://github.com/broadinstitute/inferCNV/wiki/Extracting-features ) to generate a table that will tell you which cells have what types of CNVs. You could also explore your current plot interactively by using the NGCHM extension ( https://github.com/broadinstitute/inferCNV/wiki/Next-Generation-Clustered-Heat-Map )

Regards,
Christophe.

**Comment by namit-k** [comment]
Hi @GeorgescuC ,
Thanks for your suggestions, I am able to generate expected results. 

For cases where we don't have an option of reference normal cells, do you have recommendations on what can be used as a surrogate normal cell?
thanks,
Namit

**Comment by GeorgescuC** [comment]
Hi @namit-k ,

If you know what are the normal cell types that should be present in your dataset, you can try using as the reference, cells of the same type from other experiments available that used the same sequencing technique. We have not experimented with that, but my guess is that for the infercnv processing, the overall signal should be similar enough to identify which of your cells are normal to then run infercnv on your data alone with the reference set.

Regards,
Christophe.

**Comment by namit-k** [comment]
Thank you!
