### ISSUE TITLE
How many cells can infercnv analyse,what the max number of cells?

### ISSUE THREAD

**Issue by dhoneyi** [broadinstitute/infercnv#195]
Dear,
      I am using infercnv to analyse my scRNA-seq data, I have around 30,000 cells. I think there are too many cells, I may need to downsample. So I wanna know the infercnv can analyse how many cells.Thanks.

**Comment by GeorgescuC** [comment]
Hi @dhoneyi ,

Depending on the set of options you want to use and if you only need to run infercnv once or expect to use it for multiple datasets of that size, you can downsample to different levels. 15k cells can be processed in a few days on an average system with subclustering, HMM predictions and Bayesian filtering enabled.

The main option that you have to look out for are is `analysis_mode`. If running in "subclusters" mode, the runtime will increase greatly because of the steps that calculates the subclusters (by default using random trees). If you set it to "cells", clustering is not done, but running the HMM predictions cell by cell takes a long time ("cells" is not recommended except for specific experimental designs because their is very little data for the model to work on, and it is much noisier). The `analysis_mode` option is only relevant if you want to run the HMM.

To downsample, you can use the option `max_cells_per_group=n` in `CreateInfercnvObject`. This will select up to n cells from each group based on the input annotations you provide. If you do not know how to set this for you dataset, you can try downsampling to 10k cells and run infercnv with the default analysis_mode and the HMM predictions off. This should run fairly fast and allow you to check how diverse your dataset is. If you have only one clone per group of cells (input annotation), you may not need to run subclustering for the HMM. If you have few subclones, you can downsample further for faster run time.

In addition, if you are limited in RAM on your system, you may run `scripts/prepare_sparsematrix.R` to convert your input counts matrix to a sparse matrix format saved an R object. This will reduce peak memory use when running infercnv and if you need to rerun infercnv with different options, loading the matrix again will be much faster.

Regards,
Christophe.
