### ISSUE TITLE
In 'subclusters' mode using random forest, infercnv doesn't cut the tree and give clusters

### ISSUE THREAD

**Issue by liuxl18-hku** [broadinstitute/infercnv#197]
Hi,

I tried to run infercnv to identify sub-clones of tumor based on CNV profile. Based on the final plot, it seems that infercnv does not cut the tree and give us the clusters:

![infercnv](https://user-images.githubusercontent.com/42717675/69476751-f6bff280-0e18-11ea-9b42-c34abdf4298e.png)

My questions is how to let infercnv cut tree and give us clusters based on tree-cutting.

Thank you!

**Comment by GeorgescuC** [comment]
Hi @liuxl18-hku ,

You can use the option `k_obs_groups=6` for a quick split of observations in 6 groups based on the current dendrogram. You can in addition run infercnv with `analysis_mode="subclusters"` so that the clustering is more accurate, but that will take more time to compute.

Based on your control cells, it looks like there may be 3 or 4 different populations of cells there too, so you could try using `num_ref_groups=4` to try to improve the cleanliness of the results. As it is right now, CNVs on chr6 should probably be taken with caution as there is signal for them in the control too (because of different expression profiles within it).

Regards,
Christophe.

**Comment by liuxl18-hku** [comment]
Hi @GeorgescuC 

Thank you for your detailed explain. One thing I forgot to mention, I used 0.99 version of InferCNV (because that's the one available on our server and I had some difficulties to install the most updated version).

Based on the results I've showed in my question (using `analysis_mode="subclusters"`), I did try `k_obs_groups=10`, there is still no cutting of the tree.

bless~
Xingliang

**Comment by GeorgescuC** [comment]
Hi @liuxl18-hku ,

The version you are using is most likely the issue. In the current version (1.3.1), using the example data, I can run `analysis_mode="subclusters"` with `cluster_by_groups=FALSE` and `k_obs_groups=6` and get the following:
![infercnv](https://user-images.githubusercontent.com/12964363/69653826-c5763b00-1041-11ea-9742-2b03e89bf4b4.png)

If you are having issues installing the most recent versions, we have [docker images available](https://hub.docker.com/r/trinityctat/infercnv/tags) that you can download. If your server does not allow for docker to run (because of root permissions), you can first convert it to a singularity image on a different machine with root, and then use that singularity image to run on the server.

Regards,
Christophe.

**Comment by liuxl18-hku** [comment]
Hi @GeorgescuC ,

You are right, after using updated version of infercnv, with `cluster_by_groups=FALSE` and `analysis_mode="subclusters"`, the tree can be cutted based on `k_obs_groups` by using `cutree(hcl, k=k_obs_groups)`.

A naive question, since we have already used random forest to identity sub-clusters, why bothering to use cutree, can we present sub-clusters identified by random forest directly on the heatmap.

Thank you!

**Comment by GeorgescuC** [comment]
Hi @liuxl18-hku ,

Right now it is not possible (besides setting the k_obs_groups to the number of subclusters there are, but it is not 100% guaranteed that it will match), but it would indeed make sense to. I will look into adding that feature.

Regards,
Christophe.

**Comment by liuxl18-hku** [comment]
@GeorgescuC Thank you!
