### ISSUE TITLE
How does num_ref_groups affect the final results

### ISSUE THREAD

**Issue by liuxl18-hku** [broadinstitute/infercnv#200]
Hi,

Using the `infercnv_1.3.1`

Would like to know how `num_ref_groups` affects final results.

With same set of sample cells and reference cells. I tried diff `num_ref_groups`, results looked so different:

### num_ref_groups = 1
![infercnv](https://user-images.githubusercontent.com/42717675/70198212-335ce980-1749-11ea-82f9-faae5a674f51.png)

### num_ref_groups = 4
![infercnv_1](https://user-images.githubusercontent.com/42717675/70198204-2dff9f00-1749-11ea-9ddd-f3fc16f1472d.png)

1. Why the reference heatmap looks different. In `num_ref_groups = 1` case, it seems that there are several cnv blocks, for example, chr4 and chr6. Based on those blocks, I decided using 4 reference groups, because this is what it looks like on the heatmap. However, these cnv blocks are gone after using `num_ref_groups = 4`.
2. Am I correct to use `num_ref_groups = 4` or there are some better way to judge whether I did things correctly.
3. Why final results looked so different using different `num_ref_groups`.

Thank you very much!

**Comment by liuxl18-hku** [comment]
Hi,

I think it should matter with `ref_subtract_use_mean_bounds`, with that parameter setting to `TRUE` (by default), splitting ref into grps will create a band [min(averages per grp), max(average per grp)] for normal mean, which is different with using only one ref grp, in which normal mean is just one single value.

**Comment by GeorgescuC** [comment]
Hi @liuxl18-hku ,

Basically, one of the steps of infercnv is to take the average expression in your reference cells, per group, and remove that from the observations expression (taking the closest reference group for each observation). In the case where all references are grouped together, the cell types that are less numerous in your set, do not have their specific expression patterns visible in the average of all the references, and hence, their signal is not properly removed from the observations. When you split the references in multiple groups, you allow the cell type specific expression patterns to be identified and remove from the observations.
I am attaching 2 figures that are the figure you sent with some extra manual drawings to explain what is happening.

The first one, below, is how the reference cells could probably be split, in 6 distinct groups (the bottom reference group could be split further down maybe, but it could also be experimental noise). On the right side of the figure, I have added how the reference subsets match to the observations subsets. You can see that the residual expression patterns are almost identical for the orange pair and the light blue pair, which means that when properly dividing the reference cells in groups, there should be mostly no residual expression left.
![70198212-335ce980-1749-11ea-82f9-faae5a674f51](https://user-images.githubusercontent.com/12964363/70360594-f712b180-184c-11ea-9863-d0b0c79a27c3.png)

The second one, below, is how the 4 reference groups are probably defined in your `num_ref_groups = 4` run, with the matching subsets again.
![70198212-335ce980-1749-11ea-82f9-faae5a674f51_4](https://user-images.githubusercontent.com/12964363/70360831-9afc5d00-184d-11ea-8b6f-68063f745c8c.png)

Your second comment is right, but you have to also take into account that cell types that are underrepresented in your reference cell will have their average masked by the rest of the cells, which is why it is important to split the references by cell type. In a way, not splitting references is similar to trying to compare bulk to single cell.
We usually recommend trying to define the cell types of your references before running infercnv by using methods for cell type assignments.

Regards,
Christophe.

**Comment by liuxl18-hku** [comment]
Yes, thank you @GeorgescuC , now I know why my second try with reference groups number equals 4 didn't have clean CNVs.

My understanding to separate references based on cell types is to reduce type I errors (confounded by cell types). Normal cells define a "range of normal", real CNVs should fall out of this range.

Our case is special, as we don't have real "normal samples". Why I didn't run infercnv without reference is because our cells are pre-sorted and it seems possible that more than half of them are cancerous. Therefore, I did clustering and cell types assignment first based on sets of markers. Then we pick those "normal" clusters, use them as references. It seems that some of them are wrongly defined and biased the "normal range".

Thank you!

**Comment by tinakeshav** [comment]
Hi Christophe, 
I have a related question. In cases where we have multiple reference "cell types" (annotated clusters), e.g. ("ref1", "ref2", "ref3"), does inferCNV take into account the inherent groupings? That is, will it treat the whole set as our reference or does it treat them as multiple references and takes the closest reference group for each observation for subtracting etc.

**Comment by GeorgescuC** [comment]
Hi @tinakane ,

When you have different annotations used as reference, it will treat them as multiple references and take the closest reference group for each observation yes.

Regards,
Christophe.

**Comment by tinakeshav** [comment]
Hi @GeorgescuC  --  Fantastic. Thank you for your response. Is there a way for us to see which reference group was used for our observations? Preferably from the (I presume) final objects: ```22_denoiseHMMi6.leiden.NF_NA.SD_1.5.NL_FALSE.infercnv_obj``` and ```run.final.infercnv_obj```? 

Thank you very much!! 
Tina

**Comment by GeorgescuC** [comment]
HI @tinakeshav ,

It seems like I missed your later post, sorry. Unfortunately, we don't track which reference group is used for each observation.

Regards,
Christophe.

**Comment by RENXI-NUS** [comment]
Hi @GeorgescuC , I have looked at the R codes quickly and found inferCNV is not actually trying to take the closest reference group for each observation subset based on transcriptome (e.g. euclidean distance in log-expression space). 

Looping through each gene, inferCNV will calculate the min and max of reference groups, and then compute the log-fold-change of all reference & observation cells. Please refer to below example:

![image](https://github.com/user-attachments/assets/dc313f07-e3f0-4779-b760-93ac87413f8e)


It's just after subsetting (e.g. based on cell type annotation), some groups in the reference panel are matching the CNV patterns to observation subsets.

May I ask is there a reason why inferCNV does not subtract the log-expression of the closest reference group (euclidean distance in log-expression space)?

Thanks!
