### ISSUE TITLE
How to decrease font size in plot_cnv()? It should show 16 labels but only 14 shown. 

### ISSUE THREAD

**Issue by singletrips** [broadinstitute/infercnv#211]
The pdf file is too big, so some labels are not shown in the plot.  How to change the pdf file size or how to change the label font size to show all labels?
![image](https://user-images.githubusercontent.com/31929730/73664919-3d7a6600-466e-11ea-8355-c849cc9719c4.png)

**Comment by singletrips** [comment]
When I set dynamic_resize = 1.5, it show this error" Error in plot.new() : figure margins too large" Even if I set dynamic_resize = 0.1, it shows the same error.

**Comment by GeorgescuC** [comment]
Hi @singletrips ,

Which labels are you trying to display? Most labels besides what is already shown are not displayed unless you have very few cells (<20 for reference cell names) because they would not fit, especially now that the newer versions of R prevent labels from overlapping with each other (so only the first gets displayed, then the next that is non overlapping).

To have a larger (taller) figure and use the `dynamic_resize=0.5` option (which is the base I would go off from) you should set the output format to png with `output_format="png"`. We allow the output format to be PDF, but because of the very large size of the files it generates and overall slowness of working with them (even just opening to visualize), most features are now designed for the png output.

Regards,
Christophe.

**Comment by singletrips** [comment]
@Christophe, plot_cnv() works well when I save the result in .png format. However, I need to save the plot into a pdf file. For the observed data, it should show 16 labels instead of 14 labels. The attached figure is what the plot should be like.
![image](https://user-images.githubusercontent.com/31929730/74250186-3d0a4c80-4cb8-11ea-83d0-888037bcc088.png)

**Comment by GeorgescuC** [comment]
Hi @singletrips ,

I fixed some issues with the plotting when using pdf as the output format. Can you try downloading the latest version of the code from the master branch and reinstalling, then running the plotting again?

From within R:
```R
library("devtools")
devtools::install_github("broadinstitute/infercnv", ref="master")
```

Or clone the repo/pull the latest version of the code and from within the main repo folder run :
```R
install.packages("./", repos=NULL, type="source")
```

Regards,
Christophe.
