### ISSUE TITLE
InferCNV-10X and Seurat 3.0

### ISSUE THREAD

**Issue by RiccardoBetta** [broadinstitute/infercnv#215]
Hello everyone. 
I would like to use InferCNV, starting from my scRNA experimental data, for more depth analysis about copy numbers variation. 

I have read your vignette about the creation of a readable matrix from 10x data but i cannot find @row.data and @cell.name inside my Seurat object. 

Probably because seurat updated how data are stored inside the object (just a guess). 
Can someone tell me which one are the corrects data to use for the realization of a readable count matrix?

A bit of context here might help:  inside my seurat obj i have assay, meta.data and active.ident, but no row data or cell.names.

Thank in advance, i'm really new to all of this.

**Comment by Josephinedh** [comment]
Your counts are stored in seurat_obj@assays$RNA@counts and cell names are in colnames(seurat_obj). So to create the counts_matrix you can use:
`counts_matrix = as.matrix(seurat_obj@assays$RNA@counts[,colnames(seurat_obj)])
`

**Comment by RiccardoBetta** [comment]
Thank you very much Jospehine!! :)

**Comment by GeorgescuC** [comment]
Hi,

Thank you for your reply Josephine! I have updated [our documentation](https://github.com/broadinstitute/infercnv/wiki/infercnv-10x) to add how to use the information stored in a Seurat object with version 3.0+ as we only had that for older versions.
If you only intend to use this matrix for infercnv, you are not required to use the "as.matrix()" call since infercnv allows sparse matrices (the format which Seurat also uses) as input to reduce memory use.


The active.ident field can also be useful to generate your annotation table, depending on which criteria you want to use.

Regards,
Christophe.

**Comment by jdriver509** [comment]
Can someone explain to me how to generate each aspect of the infercnv_object. It requires a raw_counts_matrix (which I think I can create with the above link and documentation in the inferCNV tutorial), but how do I create the annotations_file, the gene_order_file, and the ref_group_names file?

**Comment by GeorgescuC** [comment]
Hi @jdriver509 ,

For the gene_order_file, if you data is human, you can use the files we provide at https://data.broadinstitute.org/Trinity/CTAT/cnv/ . If your data is from another species or you prefer to use a different version, you can generate a new file following the instructions at https://github.com/broadinstitute/inferCNV/wiki/instructions-create-genome-position-file

The annotations_file is a basic table that is used to group together cells of the same type and patient/individual if you have that information. The format is described at https://github.com/broadinstitute/inferCNV/wiki/File-Definitions#sample-annotation-file . You can define cell types using marker gene analysis or another method of your choice, and define individuals from your metadata.

The ref_group_names is the list of annotation names from the annotations_file that should be used as the reference(s). For example, if for each patient you have 1 sample you know is normal and 1 from a tumor, you can set the first sample of each as part of the references, so that the second samples are compared to them.

Regards,
Christophe.

**Comment by maryam1717** [comment]
> Christophe

@GeorgescuC Thanks for the explanation. I am trying to apply InferCNV on my data but I don't have the separate normal and tumor sample. in this case how I define the reference?
any recommendation would be appreciated.

**Comment by GeorgescuC** [comment]
Hi @maryam1717 ,

If it is possible with the data you have, you can try making a UMAP and then identifying certain clusters based on marker genes/hallmark changes.

Regards,
Christophe.

**Comment by jjacob12** [comment]
Hello All,
I am excited by infercnv but have some rather basic questions for you, reflecting my lack of a strong bioinformatics/programming background. Please bear with me...

I wish to use infercnv to separate out cancer (Medulloblastoma) cells co-cultured with wild-type cerebellar organoids in a scRNA-seq experiment with thousands of cells. I have the following conditions and controls each with associated Seurat objects:
1. wild-type cerebellar organoid (generated from iPSC differentiation protocol)
2. medulloblastoma cell line grown as a monolayer
3. medulloblastoma cell line grown as a spheroid
4. medulloblastoma cells co-cultured with wild-type cerebellar organoid - it is for this condition I would like to separate cancer cells from the wild-type cells.

The wiki for infercnv mentions several inputs:

raw_counts_matrix:  the code to generate this matrix the Seurat object is shown. Would that be for condition 4?

annotations_file: There is an example annotations file on (https://github.com/broadinstitute/inferCNV/wiki/File-Definitions), but it is not clear to me how to generate this file. This question was asked by @jdriver509 above, but would like some additional help. The simplest option would be to use the data from the Seurat object for one or more of the 4 conditions above - reading further, one of @GeorgescuC answers recommends using the active.ident field to generate the annotation table. The active.ident field has the cell IDs and their cluster allocation. Could you please tell me how?

the gene_order_file input is provided by the Broad Institute.

ref_group_names is the last input. To keep things simple I wish to assign all the WT cerebellar organoid cells as 'normal'. In the 'annotations_file' do I simply populate the 2nd column with 'normal' for all the WT cell IDs? Obviously, I can only do that for the WT cerebellar organoid, but is that the right matrix to use for the 'raw_counts_matrix' input?
Thanks in advance, and apologies for the long question.
