### ISSUE TITLE
biological issue of inferCNV

### ISSUE THREAD

**Issue by honghh2018** [broadinstitute/infercnv#225]
Hi All,
      Thanks to develop this great tools for single cells CNV.
      Whether or not single cell RNA-seq runing inferCNV on RNA levels would be disturb by genes expression on each condition effectively, because CNV calling should be applied on DNA-seq in which there wasn't had expression levels obstructed.
     Is could make sense on RNA-seq data of single cell for runing inferCNV ?
     Thanks,
      Any advices should be appreciated.
      the picture showing below,reference using B cells
      
![image](https://user-images.githubusercontent.com/41668708/79035712-bb6d6700-7bf3-11ea-88a0-d49a1916fa35.png)

**Comment by GeorgescuC** [comment]
Hi @honghh2018 ,

The pattern you see in your references looks very much like the one another user sees in their result using immune cells as the single reference : https://github.com/broadinstitute/infercnv/issues/222#issuecomment-614361620

From the looks of it, there are 3 or 4 subtypes of profiles/cells within your reference group of cells. I would recommend either doing clustering on them and assigning more precise groups, or using the `num_ref_groups=3` or `num_ref_groups=4` option to let infercnv do a round of subclustering on them and use the reference groups.

Regards,
Christophe.

**Comment by honghh2018** [comment]
Hi @GeorgescuC 
    Thanks for the urgent reply, this was very helpful for me.
     Yes, the question you posted above that should be run over at first time, when we can choose the right group for next analysis.
     The advices would be good for my analysis.
      And the issue of the num_ref_group selected on the analysis can be setted at the begin of startting analysis.
         Thanks

**Comment by igordot** [comment]
I noticed a band (like the one shown here) showing up in control cells in multiple experiments. It's not always in the same chromosome, but it seems common in my experience, at least in 10x data.

Would it make sense to adjust the smoothing parameter? By default, the window is 101 genes.

**Comment by GeorgescuC** [comment]
Hi @igordot ,

Does this effect look to be consistent in which chromosomes display it for a given cell type? For immune cells, chromosome 6 expression levels may be linked to MHC genes, but looking specifically at the genes in the affected regions could hint at the reason for this effect.

You can try adjusting the window size, but unless you make it much higher or much lower, it likely won't change this effect.
The settings you can give a try to otherwise are:
- to use `smooth_method == 'coordinates'` and a `window_length=10000000` in base pairs. 
- to regenerate the plots with gene location and chromosome size proportional to their actual size (rather than equal dot width for every gene) by manually running `plot_cnv()` with the `plot_chr_scale=TRUE` setting.

Regards,
Christophe.
