### ISSUE TITLE
what is the smallest CNV size inferCNV can detect?

### ISSUE THREAD

**Issue by bioinfograd** [broadinstitute/infercnv#229]
I understand this depends on the genes present/used. But in theory, can it detect gene specific deletions? or does the algorithm need a specific number of genes grouped together to be lost/gained together thus setting a limit to the region being called?

**Comment by GeorgescuC** [comment]
Hi @bioinfograd ,

Because single cell data is very noisy (especially the newer, cheaper methods, that produce less reads), it is very difficult to be confident in results for a single gene in a given cell.
To work around this noisiness, infercnv uses a smoothing window over neighboring genes which is what allows the signal to be brought out (see the first step illustrated in the [general workflow figure](https://github.com/broadinstitute/infercnv/wiki/Running-InferCNV#infercnv-step-by-step-exploratory-execution) ). Because of this, it is very unlikely that a single gene change in a single cell will show signal. If you set your window size to a couple genes, say 11, you may start to be able to catch signal of very short events, but the confidence will still be lower.

Regards,
Christophe.
