### ISSUE TITLE
Error in UseMethod("as.phylo") : when cluster_by_groups=FALSE

### ISSUE THREAD

**Issue by danshu** [broadinstitute/infercnv#235]
Hi,

I finished running infercnv on multiple samples with "cluster_by_groups=T". Later I want to plot CNVs of selected samples, so I create a new infercnv object with only selected samples from the "run.final.infercnv_obj" and "plot_cnv" works on this new infercnv object with "cluster_by_groups=T", but failed with the following error message when I set "cluster_by_groups=F". What can I do to generate CNV plots with "cluster_by_groups=F" on this new infercnv object?

INFO [2020-05-21 12:29:25] ::plot_cnv:Start
INFO [2020-05-21 12:29:25] ::plot_cnv:Current data dimensions (r,c)=5616,776 Total=4389123.51206069 Min=0.732891840431437 Max=4.85384764398307.
INFO [2020-05-21 12:29:25] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2020-05-21 12:29:25] plot_cnv(): auto thresholding at: (0.817909 , 1.196367)
INFO [2020-05-21 12:29:26] plot_cnv_observation:Start
INFO [2020-05-21 12:29:26] Observation data size: Cells= 776 Genes= 5616
INFO [2020-05-21 12:29:26] clustering observations via method: ward.D
Error in UseMethod("as.phylo") : 
  no applicable method for 'as.phylo' applied to an object of class "NULL"
Calls: plot_cnv -> .plot_cnv_observations -> write.tree -> as.phylo

Best,
danshu

**Comment by GeorgescuC** [comment]
Hi @danshu ,

How are you creating the new infercnv object with only selected samples? The issue is likely to stem from the contents of the `new_infercnv_obj@tumor_subclusters` slot if you copied it from the initial object. You should be able to run the plotting if you set `new_inferncnv_obj@tumor_subclusters = NULL` .

Regards,
Christophe.

**Comment by danshu** [comment]
Here is how I created the new object:
expr.data <- c()
for (sample in samples) {
	expr.data = cbind(expr.data, cnv_obj@expr.data[, cnv_obj@observation_grouped_cell_indices[[sample]], drop=FALSE])
}
new_obj <- new(Class = "infercnv",expr.data = expr.data,count.data = matrix(),gene_order = cnv_obj@gene_order,reference_grouped_cell_indices = list(),observation_grouped_cell_indices = list(),tumor_subclusters = list(),.hspike = cnv_obj@.hspike)
i = 1
new_obj@tumor_subclusters$hc = list()
new_obj@tumor_subclusters$subclusters = list()
for (sample in samples) {
new_obj@observation_grouped_cell_indices[[sample]] = i:(i+length(cnv_obj@observation_grouped_cell_indices[[sample]])-1)
i <- i+length(cnv_obj@observation_grouped_cell_indices[[sample]])
new_obj@tumor_subclusters$hc[[sample]] = cnv_obj@tumor_subclusters$hc[[sample]]
for (subcluster_id in names(cnv_obj@tumor_subclusters$subclusters[[sample]])) {
new_obj@tumor_subclusters$subclusters[[sample]][[subcluster_id]] = unlist(new_obj@observation_grouped_cell_indices[[sample]][match(cnv_obj@tumor_subclusters$subclusters[[sample]][[subcluster_id]], cnv_obj@observation_grouped_cell_indices[[sample]])])
}
}

**Comment by danshu** [comment]
Can you suggest how to do the clustering on the new infercnv object?

**Comment by GeorgescuC** [comment]
Hi @danshu ,

There are a few options depending on what you are aiming to do precisely. I think the 2nd is what you are trying to do.

- If keeping the existing clustering information is not important (which sounds like it is the case as you are trying to use `cluster_by_groups=FALSE` while the run was done with `cluster_by_groups=TRUE`), you can simply set `new_inferncnv_obj@tumor_subclusters = NULL` and a new clustering will be run. The error you encounter is because the tumor_subclusters field is not null and so it expects to find clustering information for all observations together, which it doesn't.
- If you want to plot each group (samples in your case I think) of cells on a separate plot while keeping the existing clustering, you can use the method "plot_per_group" that should handle everything automatically. In this case, the value of `cluster_by_groups` would not change anything as there is only one group per plot.
- If you want to subset the initial object to a set of annotations/samples rather than only one, and want to keep the clustering information, the easiest would be to take the code of `plot_per_group` and adapt a couple sub-selections.

Regards,
Christophe.

**Comment by danshu** [comment]
@GeorgescuC   Thanks!
