### ISSUE TITLE
Unknown malignant vs normal cell type

### ISSUE THREAD

**Issue by SNRNS** [broadinstitute/infercnv#241]
Hello infercnv team,

I am wondering what is the best solution for the following scenario:

Having multiple tumor samples I can easily define normal immune and stromal cells, as well as epithelial cells.

Within the epithelial cells I expect to have cancer cells, thus I define these populations as _malignant_.

However, there is a small cluster that has low library size but seem to cluster between epithelial and stromal cells (fibroblasts). 

I want to define if these cells are cancer cells or not, thus looking at CNVs would gives us a good approximation to the most likely answer.

The question is, if I should define this cluster as _normal reference_ or _malignant_ or do something else.

I think the most conservative approach, would be to consider them as _normal reference_ and if I see CNV in these cells, then that would be a very strong evidence that they are indeed _not_ normal cells but _malignant_.

This would also apply - in the reverse way - to those cells within the epithelial compartment, that are not _malignant_, but transcriptionally are very similar to _malignant_ cells compared to the _normal_ cells. In this case I would expect to see diploid genomes within this epithelial cluster despite these cells being labeled as _malignant_.

Is this approach and reasoning correct?

**Comment by SNRNS** [comment]
Hi,

After reading further the documentation I opted for labeling the putative "EMT" cluster as *malignant* and setting the `analysis_mode=="subclusters"` to allow inferCNV to detect whether these putative cells indeed have or not CNVs and become a separate cluster or not from the epithelial *malignant* ones.

Thus I opted for running *inferCNV* this was:

```
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1,
                             out_dir=opath,
                             num_ref_groups=12,
                             ref_subtract_use_mean_bounds=TRUE,
                             cluster_by_groups=TRUE, 
                             denoise=TRUE,
                             sd_amplifier=3,  # sets midpoint for logistic
                             noise_logistic=TRUE, # turns gradient filtering on
                             HMM=TRUE,
                             HMM_type="i6",
                             HMM_report_by="subclusters",
                             analysis_mode="subclusters",
                             tumor_subcluster_partition_method="random_trees",
                             tumor_subcluster_pval=0.05,
                             diagnostics=TRUE)
```

Are these the most appropriate parameters for detecting whether a group of cells are a subclone of cancer cells instead of normal cells?

**Comment by GeorgescuC** [comment]
Hi @SNRNS , 

If you are able to define immune, stromal and epithelial cells, is that information part of your input annotations? An important early step is to have proper reference clusters, that are not a mix of different expression profiles (cell types) or too divided (increases the importance of noise). In the command you sent, `num_ref_groups=12` will groups all the cells defined as references together before splitting them in 12 clusters based on hclust, which seems too many clusters for the number of cell types you have.

As for cells you are not sure whether they are malignant or not, they should not be set as references because then any signal they have would be used to calibrate what one of the expected expression profiles is.

Regards,
Christophe.
