### ISSUE TITLE
Questions about output files

### ISSUE THREAD

**Issue by edenisen** [broadinstitute/infercnv#245]
Hi @GeorgescuC 

Thank you for developing and maintaining this great tool.

I'm new to inferCNV, and wanted to double-check if I understood the program's outputs correctly. Could you please comment on the following:

1. I understood that one way of looking at CNVs in the data is with **infercnv.png**. One can visually identify affected regions and select clusters of cells which are likely to be normal or carrying different types of CNVs. Cell order can be found in **infercnv.observation_groupings.txt** file (top row of the file corresponds to the bottom cell on the heatmap); the dendrogram shown in **infercnv.png** can be found in **infercnv.observations_dendrogram.txt** and **final_object@tumor_subclusters$hc[["all_observations"]]** - is that correct?

2. Another way of looking at CNVs is using HMM predictions: **HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat** lists CNV regions & states predicted per cell cluster (with analysis_mode='subclusters'). 

- Is it correct to use this file together with **final_object@tumor_subclusters$subclusters$all_observations** from **run.final.infercnv_obj** to get a set of CNVs predicted per cell (technically predicted on a cluster level, not cell level)? I couldn't find file **HMM_CNV_predictions.*.cell_groupings** described in https://github.com/broadinstitute/inferCNV/wiki/inferCNV-HMM-based-CNV-Prediction-Methods

- This clustering is different from the one seen in **infercnv.png**, correct? Does this clustering match the dendrograms shown in **infercnv.17_HMM_predHMMi6.rand_trees.hmm_mode-subclusters.png** and **infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.png**? 

3. I understand that **CNV_State_Probabilities.dat** includes the same regions as in **HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat**, but shows probabilities for each state and CNV. 

- Could you please comment on the relationship between **CNV_State_Probabilities.dat** and **HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat** file? 

- My first idea was to filter **CNV_State_Probabilities.dat** and find CNVs with, say, >0.5 probability in a state other than 3, and then retrieve the corresponding rows from **HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat**. But if **HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat** is already filtered (how?) as per https://github.com/broadinstitute/infercnv/issues/175, I am not quite sure how to better retrieve high-probability CNVs.

- How is **infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.png** figure related to **CNV_State_Probabilities.dat** or **HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat** file?

4. Does **infercnv.NormalProbabilities.PostFiltering.png** show yet another cell clustering, now based on probabilities of CNV not being normal?

Thank you!

**Comment by GeorgescuC** [comment]
Hi @edenisen ,

1) There are a couple ways. If you know how many clusters you would like the tree to be cut in with cutree and they are not grouped by annotations, you can use the "k_obs_groups=n" option to have the observations be split in n clusters. If they are grouped per annotation, you can still use cuttree but will need to do it manually on each annotation tree. Another way that is more interactive is to use [the interactive heatmap viewer](https://github.com/broadinstitute/infercnv/wiki/Next-Generation-Clustered-Heat-Map) and select cells from there.


2) The file with the names of cells in each subcluster should be `17_HMM_predHMMi6.hmm_mode-samples.cell_groupings`, I will update the wiki to reflect the changes.

Because the HMM predicted values are different from the values they are predicted from, with a lot of identical rows (within subclusters), the order of the subclusters in between each other will be slightly different (mostly permutations of branches), and the cells within a subclusters being identical, there order is random.


3) First, the values in `CNV_State_Probabilities.dat` are the same ones displayed in `cnvProbs.0.*.pdf`. The values in `HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat` are the HMM predicted state for each CNV (defined by a chromosomal region and subcluster of cells), while the values in `CNV_State_Probabilities.dat` are the posterior probabilities for each region of being in each state as calculated by the Bayesian filtering. You can find more details on how the later is calculated and used [on the wiki](https://github.com/broadinstitute/infercnv/wiki/Bayesian-Network-Latent-Mixture-Model).

What you want to do seems to be close to using the option `BayesMaxPNormal=0.5`, the difference being that the option will filter out CNVs with a >0.5 probability of being in state 3, rather than keep those that have a specific state that is not 3 with probability >0.5. [CNA regions identified by the HMM are filtered out if the CNA region's posterior probability of being normal exceeds a specified threshold.](https://github.com/broadinstitute/infercnv/wiki/Bayesian-Network-Latent-Mixture-Model#filtering-out-low-probability-cnvs)
`HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat` is already filtered out as explained above yes. If you want the unfiltered version to apply a different method of filtering, you should use `17_HMM_predHMMi6.rand_trees.hmm_mode-subclusters.pred_cnv_regions.dat` which is the HMM output (unfiltered) as the starting point.

`infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.png` is the result of Bayesian Filtering of the HMM predictions in step 17. The filtering is done based on the probabilities found in `CNV_State_Probabilities.dat` and `HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat` contains the CNVs left after the filtering.


4) `infercnv.NormalProbabilities.PostFiltering.png` and `infercnv.NormalProbabilities.PreFiltering.png` have the same clustering, but yes, it is different from the other plots. I will look into making the clustering be conserved across those steps.

Regards,
Christophe.

**Comment by edenisen** [comment]
Hi @GeorgescuC

Great, thanks for the clarification!

**Comment by newbieMars** [comment]
Hi @GeorgescuC,

First of all, thanks for this great tool!
I still have a misunderstanding about "groupings" between inferCNV.observation_groupings and 17_HMM_predHMMi6.hmm_mode-samples.cell_groupings.
You said thas as "the HMM predicted values are different from the values they are predicted from, the order of the subclusters in between each other will be slightly different (mostly permutations of branches), and the cells within a subclusters being identical".
Does it means that we should find the same subclusters compositions in term of cells (whatever the order), even if the order of subclusters may differ between this 2 groupings?

Thanks

**Comment by Prakrithi-P** [comment]
Hi,
Great tool! Just wondering if the default de-noising step/QC filtering steps try to filter out normal cells? I see a lot of cells that are not retained are either normal or low quality. I just ran these:

infercnv_obj = CreateInfercnvObject(
  raw_counts_matrix=GetAssayData(Mel_scRNA, slot="counts"),
  annotations_file=infercnv_meta,
  delim="\t",
  gene_order_file="/scratch/project/stseq/Prakrithi/skin_atlas/infercnv/hg38_gencode_v27.txt",
  ref_group_names=NULL) 
out_dir = tempfile()
infercnv_obj_default = infercnv::run(
    infercnv_obj,
    cutoff=1, # cutoff=1 works well for Smart-seq2, and cutoff=0.1 works well for 10x Genomics
    out_dir="infercnv/all/",
    cluster_by_groups=TRUE, 
    plot_steps=FALSE,
    denoise=TRUE,
    HMM=FALSE,
    no_prelim_plot=TRUE,
    png_res=60
)

Thanks and regards,
Prakrithi
