### ISSUE TITLE
Adaptability to 10X data

### ISSUE THREAD

**Issue by Dragonlongzhilin** [broadinstitute/infercnv#249]
Hi, 
when using to infer cnv in a 10X genomic data, I found that the modified expression is in the range of 0.85 to 1.15, not 0 to 2.
The normal cell as reference also detected by 10X. 
Is this reasonable?
Whether infercnv is not suitable for 10X? because this technology can only detect fewer gene, median gene number ~1300.

**Comment by GeorgescuC** [comment]
Hi @Dragonlongzhilin ,

Infercnv can be used for 10X data, you only need to change the filtering `cutoff` for the minimal number of average reads per gene from 1 to 0.1 . The reason the modified expression is in the range 0.85 to 1.15 rather than 0 to 2 is because we do not scale it to fit that interval anymore.

Regards,
Christophe.
