### ISSUE TITLE
How is the default number of subclusters defined when running "analysis_mode='subclusters'"?

### ISSUE THREAD

**Issue by aerickso** [broadinstitute/infercnv#263]
Hi!

Documentation in the wiki and for infercnv::run is unclear, how is the default number of subclusters defined when running "analysis_mode='subclusters'"? I've also parsed the inferCNV_tumor_subclusters.R and inferCNV_tumor_subclusters.random_smoothed_trees.R scripts, and it is not clear from there either.

To further clarify my question is there a default "hard wired" number of output tumor subclusters? If so, is it 8? And if so, why?

I'm working with datasets in the range of 5-20k cells, with 5-10k in reference. Not having any issues with compute times due to using HPC.

Example code from a recent subcluster run:

Example_InferCNV = infercnv::run(Example_InferCNV ,
                                         out_dir="~/Outputs",
                                         analysis_mode= c("subclusters"),
                                         num_threads = 10,
                                         cutoff=0.1,
                                         denoise=TRUE,
                                         HMM=TRUE,
                                         tumor_subcluster_pval=0.05)

I've noticed from my outputs, as well as [here](https://github.com/broadinstitute/infercnv/issues/222), and [here](https://github.com/harbourlab/UPhyloplot2/tree/master/Inputs): (UPhyloPlot2 takes the output 17_HMM_predHMMi6.rand_trees.hmm_mode-subclusters.cell_groupings file) that if the parameter to define the number of subclusters if left blank, that it appears that subcluster defaults to output 8 tumor subclusters. Parsing the .cell_groupings file ( and I presume the infercnv_obj@tumor_subclusters, but this would need to be verified), the subclusters have a structure as follows:

1.1.1.1
1.1.1.2
1.1.2.1
1.1.2.2
1.2.1.1
1.2.1.2
1.2.2.1
1.2.2.2

Is there a reason (biological or data driven) for specifying 8 tumor subclusters? I understand and buy using the default SHC method to define subclusters and heights, but it seems biologically improbable that tumor cells would always "group to 8".

**Comment by GeorgescuC** [comment]
Hi @aerickso ,

The method used to define subclusters is set with the "tumor_subcluster_partition_method" option, whose default value is "random_trees". You can find the checks about what methods to call and when based on the input options in R/infercnv_ops.R. With the default option, there is no "hard wired" number of clusters to define. It is however possible that something makes subclustering tend towards 8 groups in certain cell types for some reason, but it is not intentional.

In the UPhyloplot2 examples files you linked, the Immune cells have 7 subclusters.

When I run the subclustering on the example data, I get 5/3/2/4 subclusters for the different patients.

Regards,
Christophe.
