### ISSUE TITLE
 STEP 18: Run Bayesian Network Model on HMM predicted CNV's

### ISSUE THREAD

**Issue by wuzhigui** [broadinstitute/infercnv#264]
Really I like your infercnv which is a excellent software!
I got an error here.
![image](https://user-images.githubusercontent.com/70992194/95292284-c3a51700-08a3-11eb-9b79-0a24d3d9dd4b.png)

`Error in apply(cnv_means, 2, function(i) which(i == max(i))) :
  dim(X) must have a positive length`
please help me !

**Comment by GeorgescuC** [comment]
Hi @wuzhigui , 

It seems like the error occurs because there are no CNVs left after filtering, as hinted by the log "Total CNV's after removing: 0". Which version does this happen on?

Also which analysis mode are you using? If you are trying to run the HMM on all cells as a single group while there are multiple different subclones, results will not be good, and you need to use the subcluster mode.

Regards,
Christophe.
