### ISSUE TITLE
map_metadata_from_infercnv.txt is not exit in my output folder

### ISSUE THREAD

**Issue by fengwei-li** [broadinstitute/infercnv#266]
Hi,
    I want to divide all my epithelial cells(KRT19+）from tumor samples into tumor cells and non-tumor cells subclusters based on inferCNV results. Fibroblast cell(COL1A2+) from non-tumor samples were set as "reference"cells. 
    However, I met a very awkward question. I finished the infercnv, and got the infercnv plot. However, I can not find the "map_metadata_from_infercnv.txt" from my output folder. Therefore I can not get the SNV and CRS etc. 
    It appeared that the"map_metadata_from_infercnv.txt"is no longer created after the update of V1.1.2. So i ran the Step3(as follow),but got the Error information:

Step1
`infercnv_obj <- CreateInfercnvObject(raw_counts_matrix = count,
                                     annotations_file = '../cell_group.txt',
                                     delim="\t",
                                     gene_order_file = '../gene_order.txt',
                                      ref_group_names = "Fibroblast")`
Step2
`
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1, 
                             out_dir="./inferCNV", 
                             cluster_by_groups=T,   
                             denoise=T, 
                             HMM=T)
`
Step3
`
seurat <- infercnv::add_to_seurat(seurat_obj = ICC,infercnv_output_path = '../inferCNV',top_n = 10)

Error in infercnv::add_to_seurat(seurat_obj = ICC, infercnv_output_path = "../inferCNV",  : 
  "options"槽名不存在于"infercnv"类别对象中(The "options" slot name does not exist in the "InfercnV" category object)
`

Here is the inferCNV plot I got
![infercnv](https://user-images.githubusercontent.com/54225799/96566853-abe47e80-12f8-11eb-9ef0-aca35a941a6a.png)
Here is my session information
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods  
[9] base     

other attached packages:
 [1] devtools_2.3.2              usethis_1.6.3              
 [3] future_1.19.1               SingleR_1.2.4              
 [5] SummarizedExperiment_1.18.2 DelayedArray_0.14.1        
 [7] matrixStats_0.57.0          Biobase_2.48.0             
 [9] GenomicRanges_1.40.0        GenomeInfoDb_1.24.2        
[11] IRanges_2.22.2              S4Vectors_0.26.1           
[13] BiocGenerics_0.34.0         infercnv_1.4.0             
[15] openxlsx_4.2.2              dplyr_1.0.2                
[17] magrittr_1.5                data.table_1.13.0          
[19] Matrix_1.2-18               Seurat_3.2.2 

Thanks. in advance for any assistance

**Comment by GeorgescuC** [comment]
Hi @fengwei-li ,

The "map_metadata_from_infercnv.txt" output is not generated automatically, you do indeed need to run the add_to_seurat() method. The issue you have about the options slot missing should be fixed since a couple versions. I would recommand updating your version to at least version 1.5.2 if you plan to use add_to_seurat() with a seurat object as a check was added to make sure the data is transfered in the proper order in case the matrices cell order don't match exactly in between infercnv and seurat.

If you want to avoid rerunning infercnv on the new version, you should be able to edit the run.final.infercnv_obj object by reloading it and changing the contents of the infercnv_obj@options slot with the contents of the same object created on the new version, then saving it to file.

Regards,
Christophe.

**Comment by fengwei-li** [comment]
Thanks!
