### ISSUE TITLE
Question about groupings

### ISSUE THREAD

**Issue by newbieMars** [broadinstitute/infercnv#271]
Hi @GeorgescuC,

First of all, thanks for this great tool!
I still have a misunderstanding about "groupings" between inferCNV.observation_groupings and 17_HMM_predHMMi6.hmm_mode-samples.cell_groupings.
In #245, you explained that as "the HMM predicted values are different from the values they are predicted from, the order of the subclusters in between each other will be slightly different (mostly permutations of branches), and the cells within a subclusters being identical".
Does it mean that we should find the same subclusters compositions in term of cells (whatever the order of cells), even if the order of subclusters may differ between this 2 groupings?

Because when I look at infercnv.png and HMM.png (the 17/18/19 are concordent) plots (for different analysis I've already performed with different samples), the subclusters are not only permuted but have also different size. And when I cross the information in groupings, they are differents. Below one exemple,
```
        HMM_cnv_1 HMM_cnv_2 HMM_cnv_3 HMM_cnv_4
  cnv_1       909       904       178         1
  cnv_2        75       646      1537         3
  cnv_3         0         5         4       290
  cnv_4       159         0         1         0 
```
I have a second question about "random-tree" method when analysis_mode = subclusters. Which file gives us the result of this analysis? 

Thanks

**Comment by GeorgescuC** [comment]
Hi @newbieMars , 

I am not sure I understand how the table you sent is built. Could you detail how you built it and what the different cnv labels are?
The subclustering is defined before running the HMM and stored in the infercnv_obj@tumor_subclusters slot, so you can retrieve it directly from the R object and inspect it there. It should not change once defined, and be used for the plotting if defined. However, if you try to compare the subclustering between multiple runs, they will not be identical, since random permutations are not deterministic.
The .cell_groupings file contains the detail of the subclutering. The .observation_groupings file details the color bars next to the dendrogram on the left of the plot, which are the k_obs_groups cutting of the dendrogram if the option is set, and the input annotation (as seen in the legend).
If you are using a version of infercnv older than 1.3.3, the issue may be that the plotting was not using the stored subclutering information and was running the basic hclust every time.
If you are using a version older than 1.1.4, the CNV ids were reassigned between step 17 and 18 (renumbered from 1 to n after filtering), so trying to match them based on ids would not work.

The "random-tree" method produces the subclustering that you can inspect in the @tumor_subcluters slot or the .cell_groupings file.

Regards,
Christophe.

**Comment by newbieMars** [comment]
Hi @GeorgescuC , 

Thank you very much for your quick reply.
Well, for the table I've sent, it's the contingency table of my non-reference cells according to HMM subclusters and final cnv subclusters. This is the code I've used to do build it : 
```
# importing infercnv final and HMM subclusters df
infercnv_final_df <- read.table(file = "infercnv.observation_groupings.txt", 
                                sep = " ", header = TRUE)


HMM_df <- read.table(file = "infercnv.19_HMM_predHMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.repr_intensities.observation_groupings.txt", 
                     sep = " ", header = TRUE)

# Rename the infercnv and HMMi6 subclusters to differentiate it from 
infercnv_final_df$Infercnv.Dendrogram.Group <- paste0("cnv_", infercnv_final_df$Dendrogram.Group)
HMM_df$HMM.Dendrogram.Group <- paste0("HMM_cnv_", HMM_df$Dendrogram.Group)

# And cells column and select only cells and subclusters columns
infercnv_final_df$cells <- rownames(infercnv_final_df)
HMM_df$cells <- rownames(HMM_df)

infercnv_final_df <- infercnv_final_df %>% dplyr::select(cells,Infercnv.Dendrogram.Group)
HMM_df <- HMM_df %>% dplyr::select(cells,HMM.Dendrogram.Group)

# Merge the 2 tables according to cells
cells_subclusters_df <- infercnv_final_df %>% full_join(HMM_df, by = "cells")

# Generate contingency table of cells : HMM_subclusters X Infercnv_subclusters
table(cells_subclusters_df$Infercnv.Dendrogram.Group, cells_subclusters_df$HMM.Dendrogram.Group)
```
And yes I was using an old version (1.2.2), thus I haven't this .cell_groupings file. I'll upgrate to github master branch latest version of the tool. Thus I think the 2 files that I was using correspond to HC cutree according to k_obs_groups, that's right?

One last question, with the most updated version of the tool , do the infercnv.png left subclustering correpond to random-tree subclustering or to HC cutree?

And again, thank you for your reply and this great tool ;)

Estelle

**Comment by GeorgescuC** [comment]
Hi @newbieMars ,

The left clustering color bar corresponds to k_obs_groups cuts (default is 1), so the HC cutree. The subclusters are not indicated on the color bars, which is, I think, also the reason for the issue you see when counting cells (since you are using the first color bar in your code). To access the list of cells within each subcluster, you can use final infercnv_obj (or reload it from the run folder) and read the data stored in the infercnv_obj@tumor_subclusters$subclusters field.

Regards,
Christophe.

**Comment by newbieMars** [comment]
Thanks @GeorgescuC  for your answer.
I still have a remaining question concerning the final infercnv object.
In the infercnv_obj@tumor_subclusters$hc field, we have access to the dendrogram that led to the tumor subclusters groups found in infercnv_obj@tumor_subclusters$subclusters.
However, when I color one subcluster group in red and the second in black in the dendrogram, it seems that they can not form 2 subclusters. I have mentioned this with the plot in #273 
I've also noticed that these subclusters correlates with 19HMM_infercnv_obj@tumor_subclusters$hc

Thus, my question is : where do we find the dendrogram of the final tree associated to the subclusters? Does it correspond to the HMM dendrogram ?

If I'm asking that is that I need the dendrogram for phylogeny inference.

Thanks!

Estelle

**Comment by GeorgescuC** [comment]
Hi @newbieMars ,

Sorry for the delay in addressing this issue, I needed enough time to go back and check the whole step to make sure this is not an unintended but expected byproduct, and then track down the source of the issue. The issue steamed from part of the code (the tree stored in the $hc field) using one method of centering the data, while the rest (the recursion for $subclusters) using a different method of centering. Both are now consistant in the master branch and the issue should be fixed. I will be making a new release with some other changes, but until then you can install infercnv from github.

Regards,
Christophe.
