### ISSUE TITLE
No cluster pruning: simnorm_cell_Myofibroblasts.1 Error: C stack usage  7970116 is too close to the limit Execution halted

### ISSUE THREAD

**Issue by zhangqi234** [broadinstitute/infercnv#281]

**Comment by zhangqi234** [comment]
Dear developer:
      I trid to run the program by following commands:
infercnv_obj = CreateInfercnvObject(delim = '\t',
                                    raw_counts_matrix = exprMatrix,
                                    annotations_file  = '0826_inferCNV_cellAnnota.txt',
                                    gene_order_file   = 'ref_GRCh38_10X_cellranger_GTF_gen_pos_for_inferCNV_gene_name.txt',
                                    ref_group_names = c("Endothelial_cells"
                                                        ,"Myofibroblasts"))

# perform infercnv operations to reveal cnv signal

infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1, 
                             out_dir='./new_output_dir', 
                             cluster_by_groups=TRUE, 
                             denoise=F,
                             HMM=F,
                             analysis_mode='subclusters')

then, I got the following error during:
No cluster pruning: simnorm_cell_Myofibroblasts.1
Error: C stack usage  7970116 is too close to the limit
Execution halted

I had about 5K cells,So how to fix it?

**Comment by GeorgescuC** [comment]
Hi @zhangqi234 ,

Which version of infercnv are you using? Your log is surprising because you have the HMM option set to False, yet the log mentions "simnorm_cell_Myofibroblasts.1". This name refers to the data used to calibrate the HMM, which should not be generated when the HMM is set to False.

For the "C stack usage" error, please try setting "ulimit -s unlimited" from the terminal before starting R.

Regards,
Christophe.
