### ISSUE TITLE
17_HMM_predHMMi6

### ISSUE THREAD

**Issue by callaL** [broadinstitute/infercnv#285]
Thank you for developing this useful tool. I have some doubts about the running results.
1. I compared the two files：17_HMM_predHMMi6.qnorm.hmm_mode-subclusters.pred_cnv_genes.dat AND 17_HMM_predHMMi6.qnorm.hmm_mode-subclusters.cell_groupings. I found that some ’cell_group_name‘ in 17_HMM_predHMMi6.qnorm.hmm_mode-subclusters.cell_groupings were not in 17_HMM_predHMMi6.qnorm.hmm_mode-subclusters.pred_cnv_genes.dat，could you please explain it
Because I want to count the CNV of each gene in each cell, because the result calculated by HMM does not include all cells,Can I use infercnv.observations.txt results for statistics? If so, how can it be calculated? How should I understand the relationship between  infercnv.observations.txt and 17_HMM_predHMMi6.qnorm.hmm_mode-subclusters.pred_cnv_genes(regions).dat?

2. Is it first to calculate the heterogeneity, divide into different groups, and then calculate the CNV results of a certain group

**Comment by GeorgescuC** [comment]
Hi @callaL ,

1. If you look at the HMM predictions figure, do all subclusters have predicted CNVs? If a subcluster does not, it will not be listed in the .pred_cnv_genes.dat
Results from infercnv.observations.txt can also be used, however those are the residual expression values so you will need to apply your own criteria to define boundaries of CNVs. Since you want to use the HMM results, you can also take a look at the equivalent from the HMM steps "17_HMM_predHMMi6.qnorm.hmm_mode-subclusters.observations.txt".

2. Infercnv applies different operations to cells, independently of what annotation group/subcluster they are part of (the only difference is whether they are references or observations). If you want HMM predictions, it then splits them in subclusters (if the option is set, and according to the other options related to that), and each subcluster gets a set of HMM predictions.

Regards,
Christophe.
