### ISSUE TITLE
Possible to change chromosome ordering for plot_cnv function?

### ISSUE THREAD

**Issue by ms3389** [broadinstitute/infercnv#290]
Hello,

I tried changing the levels in the factor for gene order in the infercnv_obj to my desired chromosome order (e.g. 1,2,3,4,....,22,X) but it didn't have any effect on the plot.

Thanks

**Comment by GeorgescuC** [comment]
Hi @ms3389 , 

Here is an example of how to do it, making sure that the data remains consistent.

```
new_gene_order = data.frame()
for (chr_name in c("chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr18", "chr19", "chr20", "chr21", "chr22")) {
	new_gene_order = rbind(new_gene_order, infercnv_obj@gene_order[which(infercnv_obj@gene_order[["chr"]] == chr_name) , , drop=FALSE])
}
names(new_gene_order) <- c("chr", "start", "stop")
copy_infercnv_obj@gene_order = new_gene_order
copy_infercnv_obj@expr.data = infercnv_obj@expr.data[rownames(new_gene_order), , drop=FALSE]


plot_cnv(copy_infercnv_obj,
         cluster_by_groups=TRUE,
         cluster_references=TRUE,
         out_dir="./",
         output_filename="rev_chr_infercnv.png"
)
```

Regards,
Christophe.

**Comment by MelissaSaichi** [comment]
Hi @GeorgescuC , Thank you for this amazing package ! i have run the infercnv function with default parameters. At first, I did not change the chr ordering. Then, I tried to do it manually on the inferCNV object as you explained above; I had also tried to order the gene annotation file before running the function. Surprisingly, the results were quite different. When the chr were not ordered, I could see a loss in chrX, that I do not see anymore when the chr are ordered.

After Ordering Chr names:
![rev_chr_infercnv png](https://user-images.githubusercontent.com/64908825/114181524-e642e600-9941-11eb-894f-1126e483aea5.png) 

Before Ordering :
![infercnv 21_denoised](https://user-images.githubusercontent.com/64908825/114181676-17231b00-9942-11eb-800c-8e63eecbf9c3.png)
Do you have any hint for that ?
Thanks,
Melissa

**Comment by GeorgescuC** [comment]
Hi @MelissaSaichi ,

How many genes are present in chrX after the analysis is run? The most likely thing that happened is that chrX is extremely small and so the label of the next chromosome is hidden by R when plotting. In this situation what you saw as a loss in chrX was actually a loss in a different chr (the next in the original sorting), and you should still find the same chr/signal with a "different label" for the chromosome.

Because in most cases chrX, chrY and MT have very few genes, we remove them from the analysis altogether with the `chr_exclude=c('chrX', 'chrY', 'chrM')` option when creating the infercnv object.

Regards,
Christophe.
