### ISSUE TITLE
how to use epithelial cell from healthy donor as reference to infer cnv in epithelial cell from tumor patient

### ISSUE THREAD

**Issue by ShepherdZh** [broadinstitute/infercnv#293]
I used muscle cells as reference to infer the existance of cnv in epithelial cells, both in normal sample and tumor sample. (reference cells from normal/tumor sample to infer cnvs in observation cells -- normal/tumor sample, respectively.

While It appears that normal epithelial cells also have a bunch of cnv spots, and tumor epithelial cells share some of these cnv spots. 

So, my question is, can I use normal epithelial cells from normal sample to infer cnv of epithelial cells from tumor sample? 

If that is possible, my pseudo solution is:
1: compare the result of step 17_HMM_preds of normal vs tumor, and regress the same segment-celltype-specific cnvs that show up both in normal sample and tumor sample. The difficulty of which is to judge the shared cell type based on cnv, since there are two runs, and the cnv pattern may look alike, but they could not be exactly the same.
2: use normal cells as reference, but there are batch effects between them, and I cannot import the SCT transformed matrix from Seurat directly because there seems to be hspike calculations besides normalization and log transformation.

It would be great to know solutions other than that too.
Thanks!

![infercnv 17_HMM_predHMMi6 rand_trees hmm_mode-subclusters](https://user-images.githubusercontent.com/25859825/105814266-17bb3f00-5fec-11eb-97ad-41b86d48c8d7.png)
ctrl↑
![infercnv 17_HMM_predHMMi6 rand_trees hmm_mode-subclusters](https://user-images.githubusercontent.com/25859825/105814289-21dd3d80-5fec-11eb-86d2-864cc3161656.png)
cancer↑

**Comment by GeorgescuC** [comment]
Hi @ShepherdZh ,

If I understand correctly, you did normal muscle as reference vs normal epithelial as observation for experiment A, and tumor muscle as reference vs tumor epithelial as observation for experiment B. Is that correct?
If yes, cnv spots you find in normal epithalial (A) should be due to cell specific expression patterns and differences in genes expressed, which is why we recommend using the same cell type for reference (normal) and observation (tumor).

I suggest also taking a look at the residual expression figures as a control before trusting the HMM results, as issues in the subclustering can affect the quality of the predictions.

1: If you remove the patterns found in A from the results of B, you should be closer to the truth yes. However there could still be differences to comparing normal vs tumor of the same cell type, in part because of the step that selects which genes are above the expression threshold. Some genes that are expressed at lower levels could be dropped while they would not when using a single cell type, and genes only being expressed in the one cell type will add sparsity to the part of the matrix corresponding to the other cell type. These gene selection biases can then in turn influence the expression smoothing.

2: If using the residual expression results/figure is an option for you, those do not use hspike calculations.

Regards,
Christophe.

**Comment by ShepherdZh** [comment]
Thanks alot for your clear explanation!

**Comment by mjakobs** [comment]
Hi @GeorgescuC ,

Can you elaborate on option 2 here? Would it be appropriate to use SCT transformed counts from an integrated data set for this type of analysis (i.e. where reference epithelial cells are from a healthy donor are compared to tumour epithelial cells from another)? 

Thanks in advance for your help!
