### ISSUE TITLE
Secondary annotations for infercnv heapmap?

### ISSUE THREAD

**Issue by E-mak11** [broadinstitute/infercnv#294]
Hi, 

Thank you for the very useful tool. I have a question concerning the infercnv heatmap. As you know, the cellannotation.txt file contains the cell IDs, which match the cell matrix file, along with cell type annotations for each cell ID. I was wondering if there is any way of including a second type of annotation? For example, a third column in the cellannotation.txt file that has patient-specific sample ID's so that each annotated cell type can be matched to each patient by a colored bar, similar to the colored bars right below the dendrogram that matches each cell type's CNVs. I apologize in advance if my explanation is unclear. 

Thank you!

**Comment by GeorgescuC** [comment]
Hi @E-mak11 ,

There is no option to add a 3rd column, however to achieve what you describe you could simply combine the information from both columns into a single one. The "cell type annotation" is only used for very simple things:
- define which cells are to be used as the reference and define how many different profiles of references are present (so that we can match in the observations which group of references it is closest to)
- in observations, they are used to define the colored bars you are referencing, and pre-group cells per type/patient if you want to use the HMM predictions (in samples mode, or refining the groups further with subclustering within each of them)

The example data used in the wiki and provided with the package shows in the observations the groupings based on the patient, not the cell type.

Regards,
Christophe.
