### ISSUE TITLE
Enhancement for parallel computing base R functions 

### ISSUE THREAD

**Issue by ShanSabri** [broadinstitute/infercnv#298]
It seems that many of the time consuming base R functions can easily be parallelized.. Take for example [this](https://github.com/broadinstitute/infercnv/blob/7194b1246ad782a6658c6cdc84416c04b70040aa/R/inferCNV_ops.R#L1583) line which utilizes `lapply` to subtracting expr per gene. These sorts of functions can be easily parallelized using the `parallel` R package. Simply swapping `lapply(...)` with `parallel::mclapply(..., mc.cores = parallel::detectCores() - 1)` will speed things up quite a bit. Just a thought.

**Comment by GeorgescuC** [comment]
Hi @ShanSabri ,

Thank you for the suggestion. This is indeed something that can be done, while also keeping a fallback to lapply when using a single core, because the parallelization methods in R seem to make errors more likely in certain cases, even when set to 1 thread (as seen in the reports of issues in the Bayesian network step). It has not been a priority for now as there were much bigger bottlenecks to improve on such as the method of plotting and subclustering that have been drastically improved over with newer versions, making parallelization now more interesting.

Regards,
Christophe.

**Comment by ShanSabri** [comment]
Great!
