### ISSUE TITLE
Interpretation of results from 'infercnv.observations.txt'

### ISSUE THREAD

**Issue by WWJiaxuan** [broadinstitute/infercnv#300]
Hi,

Thanks for your useful package!

I finished funning `infercnv::run`, and got the result file 'infercnv.observations.txt'. However, I am confused about how to interpret it. Could you please give some suggestions?

We have 6 state corresponding to addition/deletion of copies in i6 HMM, do we have similar rules to interpret the result file 'infercnv.observations.txt'? For example, value in the interval [0,0.5]: completely loss?

Thanks in advance and looking forward to your reply!

**Comment by GeorgescuC** [comment]
Hi @WWJiaxuan ,

One of the goals of the HMM is to make interpretation easier, specifically for the different levels of gain/loss, by estimating what the different levels of change look like with in-silico change of sampled references. When looking at the residual expression values, it is easiest if there are multiple levels of gains or losses, which will usually be 1 and 2 gains/losses. If there is only one level, you can use the HMM assignment for the fold change assignment at least, even if you are not happy with the defined subclusters/regions.

In the future we are looking into other methods of determining the change level, but they are not ready yet.

Regards,
Christophe.

**Comment by WWJiaxuan** [comment]
Hi @GeorgescuC ,

Thanks very much for your reply!

I guess I will use the HMM assignments at the current stage. I am not sure whether my understandings to the output files are correct, may I double check with you?

1, Three files `infercnv.17_HMM_predHMMi6.hmm_mode-samples.observations.txt` , `17_HMM_predHMMi6.hmm_mode-samples.infercnv_obj@expr.data` and `expr.infercnv.17_HMM_predHMMi6.hmm_mode-samples.dat` are the same HMM prediction matrix (they may only differ in the order of cells/genes)

2, Three files `infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.observations.txt`, `18_HMM_pred.Bayes_NetHMMi6.hmm_mode-samples.Pnorm_0.5.infercnv_obj@expr.data` and `expr.infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.dat` are also the same HMM prediction matrix (they may only differ in the order of cells/genes)

3, If I would like to use the 6-state HMM predictions, which file is more appropriate for this purpose? Could you elaborate a little bit more on these files? Or can you offer your suggestions? Since I am still confused which file to use.
(a) `expr.infercnv.17_HMM_predHMMi6.hmm_mode-samples.dat`
(b) `expr.infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.dat`
(c) `infercnv.17_HMM_predHMMi6.hmm_mode-samples.observations.txt`
(d) `infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.observations.txt`
(e) others?

I apologize for some many questions, but I really want to make full use of these generated results.

Thanks in advance and looking forward to your reply!

Best regards,
Jiaxuan

**Comment by GeorgescuC** [comment]
Hi @WWJiaxuan ,

1. They are all written from the same step/results, however the ".observations.txt" file is the subset of cells from the whole matrix, more precisely those that are not references (so they are the ones from the lower heatmap).

2. Same answer as for 1.

3. Results (a) and (c) are the initial results of the HMM predictions. Results (b) and (d) are the same results but filtered to a given confidence that they are not actually normal, and are indeed CNVs/CNAs. You can read more about this filtering [on the wiki.](https://github.com/broadinstitute/infercnv/wiki/Bayesian-Network-Latent-Mixture-Model#filtering-out-low-probability-cnvs)
Besides that, (a) and (b) are the results for all cells, while (c) and (d) are only the results for the observations (lower heatmap).


One important thing to note if you are going to use the HMM results is to make sure that the HMM results appear to match the residual expression results from infercnv.png. Since you are running inferCNV in "samples" mode, all cells that have the same annotation get the same predictions, but this is not necessarily representative of the cell heterogeneity, as there could be multiple different subclones in one annotation. If your results do not appear to match, you should run the HMM in subclusters mode.

Regards,
Christophe.
