### ISSUE TITLE
Extraction interesting cells with deletion from infercnv results

### ISSUE THREAD

**Issue by EllaGoldschmidt** [broadinstitute/infercnv#301]
Hi,
I am working on a data set of HUMAN T cells. I ran infercnv with the reference being the WT compared to CRISPR treated cells. The results shows that in chromosome 14 there is a deletion.
![image](https://user-images.githubusercontent.com/64609161/109024150-1d2ca780-76c6-11eb-99b9-6ac4b22f841c.png)

I was wondering if there is a was to identify and extract the cells that have this deletion and if so how? The purpose is to identify those cells by their barcode.
I have the Newick format but since there are no subclusters it impossible to identify the specific split in the dendrogram and extract the barcodes from there. are you familiar with another way?

Thanks,
Ella

**Comment by GeorgescuC** [comment]
Hi @EllaGoldschmidt ,

You can either: 
- use the subclustering methods provided by infercnv (in which case I recommend updating to the master branch to have the new leiden method, which is much faster and provides an easily tunable parameter for the stringency of clusters) to then select the matching one.
- calculate the sum of residual expression on chromosome 14 across each cell, then select the cells that have the significantly lower total (if you plot the distribution of sums, there should be a first peak around the cells with a full chromosome loss, a high peak around the normal, and a small peak around the few cells that have gain signal).

Regards,
Christophe.

**Comment by EllaGoldschmidt** [comment]
Hi,
Thank you for the response, I used what you suggested in the second point and it looks like its working.

- About the first point, the package that is downloaded to R doesn't contain the code in the master branch? 

- Another problem I stumbled upon is the merge back to Seurat object, I used "infercnv::add_to_seurat" method and if finished with no errors but the result is not good, all the values in the meta data that were added are all 0-s and FALSE. is there a way to fix it? is it a result of a bad output of the  "CreateInfercnvObject" and "run: methods?

- Also I noticed that the expression matrix that is calculated by the infercnv is different than the original one that was inserted as an input to the function. what is the reason for that? I hoped that as a result of "infercnv::add_to_seurat"  I will be able to run further analysis on it with Seurat functions such as "FindMarkers" but it seems that the only change is that there is a duplication of the RNA matrices in the assay and not an addition of the exp matrices of the infercnv object. do you know how I might be able to fix it?

Thanks,
Ella

![meta_data](https://user-images.githubusercontent.com/64609161/110622978-db5f2f00-81a4-11eb-9f50-35b7e8c6162d.png)

**Comment by hartlama** [comment]
I'm having the same issue as Ella where my add_to_seurat output has all 0s and FALSEs. Looking forward to some ideas on this problem. 

Thank you

**Comment by GeorgescuC** [comment]
Hi @EllaGoldschmidt ,

. The package you can download from BioConductor is only updated when the version number is increased. For now as the base docker image for bioconductor-devel produces warnings from other packages, we did not increase it yet.

. Have you checked that all the values are 0/False with sum() or any()? The preview you posted only shows the 6 first values out of 13755 for 3 chromosomes, most of which are expected to be 0/False because they represent lack of CNVs in a given chr/cell intersection.
If you look at the HMM figures generated with your run, do you see signal?

. The infercnv@expr.data field is expected to change as the steps go, otherwise there would be no analysis. You can keep track of how they change by enabling the "plot_steps" option. The original counts are stored in the infercnv@count.data field for use in the steps that require them.
The method that interacts with Seurat only adds meta.data fields to the Seurat object with the same results that you can find in the "map_metadata_from_infercnv.txt" file, but you are free to export the infercnv@expr.data field to Seurat manually if you want to do further analysis based on it.

Regards,
Christophe.
