### ISSUE TITLE
The same cluster show different CNV 

### ISSUE THREAD

**Issue by zqyhyunbin** [broadinstitute/infercnv#302]
I am sorry just a little bit confused why one cluster shows two types of CNV, does that means it contain more subcluster? The result like the below:
<img width="459" alt="Snipaste_2021-02-27_14-41-43" src="https://user-images.githubusercontent.com/22170089/109377994-18583580-790a-11eb-844c-6221835e8356.png">

Thank you so much

**Comment by GeorgescuC** [comment]
Hi @zqyhyunbin ,

Yes, that seems to be the case here and is a common occurrence. There are different methods to subdivide groups of cells with the same annotation, but in your case the easiest would be to set option "k_obs_groups=2" so that the hierarchical clustering is split in 2 at the first branch.

Regards,
Christophe.
