### ISSUE TITLE
choice of reference and UMAP generation from inferCNV output

### ISSUE THREAD

**Issue by dwkarjosukarso** [broadinstitute/infercnv#305]
Hi,
thank you for developing such a nice tool. I am new to inferCNV and after trying out a few things, I would like to clarify a few things, just to make sure I understood and use it in the right way.

- My data is generated with by sequencing the 3'end of primary cancer cells (obtained from patients) with four different treatments. As these cells are purely malignant population, I am trying to use primary keratinocytes (a non-malignant cell type with kind of similar properties and cultured in the same way)
as reference cells (generated also with 3'end sequencing, but diffferent sequencing depth). Is such design actually fine for analysis with inferCNV? Or do I better use the ref_group_names = NULL?

Current code: 
ref <- read.csv(PATH_TO_REF_COUNTS)
obs <- read.csv(PATH_TO_OBS_COUNTS)
infercnv <- CreateInfercnvObject(raw_counts_matrix= counts, annotations_file = annot, gene_order_file = gene_order, ref_group_names = "normal_KNP")

infercnv_group_subclusters <- infercnv::run(infercnv, cutoff=0.1, out_dir = "infercnv_group_subclusters", 
                              cluster_by_groups = T, num_threads = 15, HMM= T, analysis_mode = "subclusters",
                              denoise= T, BayesMaxPNormal = 0.5, plot_probabilities = T, no_prelim_plot = T,
                              )

annot structure example (with A,B,C,D refers to the 4 different treatments and KNP to normal keratinocytes used as ref):
         x            y
1 A_1_0005 malignant_A
2 B_1_0011 malignant_B
3 C_1_0015 malignant_C
4 D_1_0018 malignant_D
5 KNP_1_0019 normal_KNP

							  
- We would like to extract 3 layers of information from the datasets (gene expression at RNA level, antibody-derived tags and CNV) and generate UMAPs from each layer. For the RNA and ADT data, I am currently using Seurat. I saw that it is possible to input the inferCNV output into Seurat, but I am confused as to which output do I need to input and generate UMAPs from. Is it the infercnv.observations.txt?

Thanks a lot for your help!

Cheers,
Dyah

**Comment by GeorgescuC** [comment]
Hi @dwkarjosukarso ,

Regarding the difference of sequencing depth, infercnv does try to account for variation, however if the difference in sequencing depth is too high, dropout may start to be mixed with a loss CNV if the lower depth is for the malignant population. If you do not provide any group as reference but still include the cells in the analysis, the normalization will be the same, however the "normal" level of expression will be taken over all cells rather than just the reference.
You can also decide to run infercnv with exclusively the malignant cells (by removing the KNP cells from the input matrix and annotation) and no reference, in which case only the differences between all malignant populations will be identified. This means any CNV common to all populations will not be identified. This may be interesting in your case since you are comparing treatments.

For the annotations file, you do not need headers on either columns or rows, simply the name of cells and the annotation.

For integrating the infercnv results into Seurat, there is an infercnv method called "add_to_seurat" that takes as input the run folder and the Seurat object, then adds the HMM results into new metadata fields of the Seurat object. You can then use those fields to highlight cells having certain properties on a UMAP/tSNE generated with Seurat itself. More details can be found [on the wiki.](https://github.com/broadinstitute/infercnv/wiki/Extracting-features)

Regards,
Christophe.
