### ISSUE TITLE
extract matrix after de-noising for external plot

### ISSUE THREAD

**Issue by rr1859** [broadinstitute/infercnv#308]
Hi, 

Thanks for building this great tool! I would like to add some additional annotations to the heatmap and I was wondering if the final matrix after de-noising is saved as an output after infercnv::run. 

Ramya

**Comment by GeorgescuC** [comment]
Hi @rr1859 ,

Yes, the denoised results are the outputs generated at the end of the run as long as you did run the denoising. You can find them in `infercnv.observations.txt` `infercnv.references.txt`, or you can read the object saved at the end of the run with `infercnv_obj = readRDS("run.final.infercnv_obj")` and access the data directly from the object in the `infercnv_obj@expr.data` slot. You can identify which rows are references and observations based on the data in the `infercnv_obj@reference_grouped_cell_indices` and `infercnv_obj@observation_grouped_cell_indices` respectively.

Regards,
Christophe.

**Comment by plijnzaad** [comment]
Dear infercnv team, 

I find differences between these two ways of getting at the original data. The following should produce identical values (upto 1e-9 or so round-off error), right?

```
## reading from the *.txt files:
refexp <- as.matrix(read.delim(file="infercnv.references.txt", sep=" "))
obsexp <- as.matrix(read.delim(file="infercnv.observations.txt", sep=" "))

## extracting from the infercnv object:
cnv <- readRDS("run.final.infercnv_obj")
refexp2 <- as.matrix(cnv@expr.data[ ,
   unname(unlist(cnv@reference_grouped_cell_indices)) ])
obsexp2 <- as.matrix(cnv@expr.data[ ,
   unname(unlist(cnv@observation_grouped_cell_indices)) ])
stopifnot(setequal(colnames(refexp), colnames(refexp2)))
stopifnot(setequal(colnames(obsexp), colnames(obsexp2)))
## put in same order
refexp2 <- as.matrix(refexp2[ rownames(refexp), colnames(refexp) ])
obsexp2 <- as.matrix(obsexp2[ rownames(obsexp), colnames(obsexp) ])
stopifnot(identical(dimnames(refexp), dimnames(refexp2)))
stopifnot(identical(dimnames(obsexp), dimnames(obsexp2)))
```
However I do get differences that are too large for comfort:

```
range(refexp)   ## => 0.8675488 1.1324512
range(obsexp)   ## => 0.8675488 1.1324512 identical, can that be?? The cellids of both sets are mutually exclusive 
range(refexp2)  ## => 0.8161623 2.7456173
range(obsexp2)  ## => 0.7995694 3.3889812

range(as.matrix(refexp2 - refexp))  ##  => -0.05138655  1.61316606
range(as.matrix(obsexp2 - obsexp)) ## => -0.0679794  2.2565299
```
By and large the results are comparable but which of the two ways should I be using ? 

This is `infercnv` version 1.12.0, R version 4.2.2 on a Mac.

**Comment by GeorgescuC** [comment]
Hi @plijnzaad ,

Sorry for taking so long to answer, I missed your post since it was in an already closed issue.

When running plot_cnv(), there is an option called "x.range" that limits the min/max values that are plotted to avoid outliers skewing the color breaks and toning down all color intensities. By default, it is set to "auto", which sets the min/max limits to respectively the 0.01 and 0.99 quantiles of the values in cnv@expr.matrix, setting the outliers to those limit values and effectively reducing the range() of the values in the .txt files.
You can verify this by redoing the final plot and setting the x.range option to values outside the total range of your residual expression by running `plot_cnv(cnv, output_filename = "remake_final", write_expr_matrix = TRUE, x.range = c(0.7, 3.4))`. You can then rerun the code you posted with the new .txt files as input and this time the values should match.

If you want to take a look at the code, on the current master branch it between lines 150 and 183 in R/inferCNV_heatmap.R .

So if you want to use the exact residual expression values, you can take those from the infercnv_object@expr.data field. Those that are generated along with the plots are potentially affected by plotting options.

Regards,
Christophe.
