### ISSUE TITLE
--save flag causes error

### ISSUE THREAD

**Issue by RichardsLaura** [broadinstitute/infercnv#31]
When I try to run the following script with "--save TRUE": 
>./scripts/inferCNV.R \
> --ref_groups "1:50,51:95" \
> --cutoff 1 \
>  --noise_filter 0.2 \
>  --output_dir quickstart \
>  --ref example/normal_cells.csv \
>  --vis_bound_threshold "1,-1" \
>  --save TRUE \
>  example/oligodendroglioma.tp100k.expr.matrix \
>  example/gencode_v19_gene_pos.txt 

I get the following error:
>Error in optparse::parse_args(pargs, positional_arguments = 2) :
> required at most 2 positional arguments, got 3
>Execution halted

This error disappears when I remove the --save option from the command. Any advice on a way around this? Thanks!

**Comment by GeorgescuC** [comment]
Hi @RichardsLaura ,

From the command line you sent, it looks like you are using slashes "/" instead of backslashes "\" (the escape character for the new line) so it tries to run the script with a slash as single argument. If you replace the slashes at the end of every line with backslashes it should work.

Regards,
Christophe.
