### ISSUE TITLE
expected run time

### ISSUE THREAD

**Issue by AlexanderAivazidis** [broadinstitute/infercnv#310]
Hello,

I am running inferCNV on a 10x data matrix with about 30000 cells and 20000 genes. I am using 24 cores and yet the algorithm is stuck at this point for 48 hours:

![image](https://user-images.githubusercontent.com/46488185/113161131-0255d180-9236-11eb-8106-591b4390e717.png)

Is this expected? Do you know how long it usually takes to run inferCNV on a matrx of this size?

I have installed inferCNV using singularity:

singularity shell --writable-tmpfs -e -B `pwd` infercnv.1.3.5.simg 

And ran the algorithm like this:

require(infercnv)

infercnv_obj = CreateInfercnvObject(raw_counts_matrix="10x_matrix.txt", annotations_file="10x_annotation.txt", delim = "\t", gene_order_file = "gencode_v19_gene_pos.txt", ref_group_names = NULL)

infercnv_obj = run(infercnv_obj,                   
                 cutoff=0.1,
                 out_dir='output_10x/',
                 ref_subtract_use_mean_bounds=TRUE,
                 cluster_by_groups=TRUE, 
                 denoise=TRUE,
                 sd_amplifier=3,  # sets midpoint for logistic
                 noise_logistic=TRUE, # turns gradient filtering on
                 HMM=TRUE,
                 HMM_type="i6",
                 num_threads = 24,
                 tumor_subcluster_partition_method="random_trees",
                 tumor_subcluster_pval=0.05,
                 analysis_mode = 'subclusters',
                 HMM_report_by = 'subcluster',
                 diagnostics=TRUE)

I have no prior information about clusters, so all cells are simply set to 'malignant' in the annotation file and I hope to see which cells are normal based on the CNV results.

Thanks!

**Comment by GeorgescuC** [comment]
Hi @AlexanderAivazidis ,

The "random_trees" subclustering method becomes very slow on large clusters because it performs a large number of hclust on permutations of the data, so this is not unexpected. To get around this issue, we added a new subclustering method that uses the leiden algorithm. You can install it by updating your [infercnv installation using the github master branch.](https://github.com/broadinstitute/infercnv/wiki/Installing-infercnv#option-d-install-infercnv-from-within-r-using-devtools)


Regards,
Christophe.
