### ISSUE TITLE
retrieving the genes in CNV regions

### ISSUE THREAD

**Issue by gufranca** [broadinstitute/infercnv#312]
Hi,
Thank you for providing this amazing tool! I am a newbie using it, but I could start with the basics. I've got clones in my data with different CNV profiles. Analyzing the single-cell RNA-seq data I am finding that some of the clones also have different transcriptional states (i.e., the CNV clones match the RNA expression clusters (seurat) -- which is something I wasn't expecting actually). 

So I am wondering whether the up or downregulated genes found by differential expression significantly overlap with CNV gains and loss regions, resulting that a possible explanation for up/down regulation would be related to copy number gains/losses of those genes. 

Does that hypothesis make sense? If so, how could I retrieve the genes that "fall" in the inferred CNV regions from inferCNV outputs? Therefore, I could do some hypergeometric test to check whether the diferentially expressed genes and genes in CNVs are overlapping.

* As a side question: Because CNVs seem to match the transcriptional states, would it be possible that inferCNV is actually capturing the global epigenetic changes rather than copy number variation?

Thank you very much for any advice.
Gustavo

**Comment by GeorgescuC** [comment]
Hi @gufranca ,

In essence, infercnv looks for concordant, co-localized changes in expression level, so it is possible for both to align yes. The clearest example would be if a CNV region is a loss of both copies, in that case there can be no expression anymore for all the genes in that CNV. 

To retrieve the genes part of a CNV region, the easiest is to run infercnv with the HMM. If your annotations match with the clonality of cells, you can keep the analysis mode to samples, but otherwise you should use the subclustering so that each subclone gets its own set of predictions.

For your side question, one of the steps that infercnv uses to bring signal out from the single cell noise and gene specific variation is the smoothing step, where the expression is averaged over a window size (in number of genes by default). This means that for any epigenetic change to be captured it would need to affect tens of neighboring genes in the same manner/direction, but not all genes from the the cell either, or it would be confused with a difference in sequencing depth.

Regards,
Christophe.

**Comment by gufranca** [comment]
Thanks, Christophe!
