### ISSUE TITLE
Dendrogram file and cell groupings file produce different phylogenetic trees

### ISSUE THREAD

**Issue by harbourlab** [broadinstitute/infercnv#322]
Plotting a phylogenetic tree from the dendrogram.txt (newick format) and comparing it to trees generated from the "cell_groupings" file produces different outcomes. Shouldn't they be the same? Thank you in advance!! (The reference cells were removed from the cell_groupings file before plotting, both trees have the same amount of cells with same cell IDs, and we trimmed the dendrogram branches to have the same amount of depth (4 nodes))

<img width="541" alt="Screen Shot 2021-05-03 at 3 51 36 PM" src="https://user-images.githubusercontent.com/29413858/116925665-76193e80-ac27-11eb-9e59-ea805d6cd1ef.png">

**Comment by GeorgescuC** [comment]
Hi @harbourlab ,

The cell_groupings file is based on the subclustering while the newick dendrogram is a simple hclust of the data based on the input groupings (if cluster_by_groups is true, with one tree per group) or of all the cells.
I do not think this is the issue you have here, but please keep in mind that depending on the options you give to the plot_cnv method, a newick tree may be regenerated on the fly rather than using the one already stored in the object if the options are not compatible (such as flipping the option to group based on input annotations), so it may not match for that reason. 

For the cell_groupings file, by default until recently, the subclustering was done using the random trees method, which meant that the overall structure should have been the same as the initial newick/hclust, however there was an issue (fixed in v1.7.2+) that the centering method applied during the random tree subclustering was different to that applied to the overall tree, so the tree could be more or less different. This is I think the case you are in.

Of note too, the new (and now default) subclustering method that allows for much faster runtimes using the Leiden algorithm will not generate trees in the cell_groupings file, but directly groups, as it is based on community detection in a network rather than hierarchical clustering.

Regards,
Christophe.
