### ISSUE TITLE
Re-scale chr_length

### ISSUE THREAD

**Issue by angelussong** [broadinstitute/infercnv#326]
Hi, 

Thanks for your time! I am trying to match my inferCNV results to the WES CNV calling results. However, the chr lengths were scaled differently so it was difficult to see clearly the comparison/validation. 

I saw in the documentation that chr_lengths could be given as a named list within plot_cnv() so I am now trying to use that to make the inferCNV heatmap chromosomal lengths consistent with the IGV view (which is the actual scaling of chr lengths I believe). 

So I went back in the inferCNV_heatmap.R source code to see how the chr_length was defined and here is what I found: 

```
chr_name_list = unique(infercnv_obj@gene_order[["chr"]])
for (chr_name in chr_name_list) {
  chr_lengths = c(chr_lengths, max(infercnv_obj@gene_order$stop[which(infercnv_obj@gene_order$chr == chr_name)]) + 10000)
}
names(chr_lengths) = chr_name_list
```
This is the chr_lengths by default: 
![image](https://user-images.githubusercontent.com/40570906/118076801-b8e5bf80-b367-11eb-8bcd-d1da99692862.png)

Therefore, I mimicked the format/type of chr_lengths to make the named list that I want. 
![image](https://user-images.githubusercontent.com/40570906/118076825-c602ae80-b367-11eb-967d-dd272e11fe90.png)

However when I ran plot_cnv() with this chr_lengths, (I also turned on plot_chr_scale to be True), I ran into this error: 

`INFO [2021-05-12 18:37:05] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2021-05-12 18:37:06] plot_cnv(): auto thresholding at: (0.916093 , 1.089924)
INFO [2021-05-12 18:37:07] plot_cnv_observation:Start
INFO [2021-05-12 18:37:07] Observation data size: Cells= 418 Genes= 8055
INFO [2021-05-12 18:37:07] plot_cnv_observation:Writing observation groupings/color.
INFO [2021-05-12 18:37:07] plot_cnv_observation:Done writing observation groupings/color.
INFO [2021-05-12 18:37:07] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2021-05-12 18:37:07] plot_cnv_observation:Done writing observation heatmap thresholds.
Error in image.default(gene_position_breaks, seq_len(nr + 1), x, xlim = 0.5 +  : 
  increasing 'x' and 'y' values expected`

Seems that the "colors for break" step is broken I guess? 
Could you please help me with this or do you happen to have an example how to re-scale the chr_lengths in the heatmap? 

Thanks so much for your help!

**Comment by angelussong** [comment]
A little update, I think the error is due to that the chr length in the new chr_length has to be larger than the default value. So I managed to bypass this error by scaling the chr_length accordingly and got some figures generated. However, I found that by doing so, only the last running window got expanded, not the entire chromosome. I'm wondering now if there's any other parameter I could tweak with so that all the running windows within one chromosome could be expanded proportionally so that after scaling the chromosome, the CNV pattern could maintain. 

Thanks!

**Comment by GeorgescuC** [comment]
Hi @angelussong ,

The reason why the new chr lengths have to be larger than the default value is because the position of the genes provided as input when running infercnv matters when rescaling the heatmap. Every gene still present in the final results (so genes that did not get filtered out because of not being expressed) needs to fit somewhere on the rescaled chromosome, you can't have a gene sitting outside of the rescaled chromosome. This is also why the default value used if no list of lengths is provided is the end position of the last gene on each chromosome plus a small margin.

For your comment about only the last running window being expanded, I am not sure I understand what is happening. Plotting using the option to resize the chromosomes does not change the results nor the content of the object plotted. However, the default smoothing method operates on a number of genes distance, regardless of how far in base pairs they are on the (same) chromosome, so for example genes on both sides of the centromere are still considered direct neighbors. This can have a noticeable impact on the resized heatmaps if the expressed genes are very unevenly spread over the chromosomes/have widely different densities. One thing with the workaround you described is, if for example you multiplied the chr length by 10, the extension that is 9 times the actual size will be just the last gene, as the breaks between genes are (end(i) + start(i+1))/2.


Regards,
Christophe.
