### ISSUE TITLE
It it ok to use stromal cell clusters as reference when I want to test against probable epithelial tumor cell clusters?

### ISSUE THREAD

**Issue by kaizen89** [broadinstitute/infercnv#331]
Thanks a lot for making this package.
I have clustered data where I annotated clusters as `stroma` or `epithelilal`. For the reference clusters I used some of the stormal clusters. It it what would you reommend? Based on what I read, different cell types can have different CNV. Although I see clearly different CNV in epithelial clusters vs stroma, one could interpret this as just a difference between epithelial cells and stromal cells and not tumor vs normal cells.
What are your thoughts about this?

**Comment by GeorgescuC** [comment]
Hi @kaizen89 ,

Ideally you should set some cells you know are healthy and of each of the present cell types as reference. It is not guaranteed that simply comparing healthy cells of different cell types would result (one as references the other as observations) would display any CNV signal, however it is not guaranteed that it won't either, the result is down to the specific cell types and their expression profiles.

For the stromal cells, are the ones you set a reference known or identified to be healthy? If yes the results for stromal cells should be good.

For epithelial cells, assuming you do not have information about which cells are healthy, do you have any information about whether any healthy cells are expected to be present in this sample? If you know there should be at least a given proportion of epithelial cells that are healthy, then if there is cnv signal across all the epithelial cells, it would indicate that at least part of it is indeed due to cell type differences.
If you do not have any information about the sample, you could try intregrating data (with Seurat for example) from a different experiment/study that uses the same type of sequencing and has identified epithelial healthy cells (having stromal cells too would give you a control) that you can then use as your epithelial reference.

Regards,
Christophe.
