### ISSUE TITLE
Working with inferCNV without normal cell reference

### ISSUE THREAD

**Issue by yana123668** [broadinstitute/infercnv#334]
Dear inferCNV team,

I only just started working with inferCNV and I am experiencing some issues in actually creating the inferCNV object in the first place and I was hoping you could answer my questions.

1) I only have tumour samples in my dataset and I found out that you can use GTEx data sets as a reference for normal cells, but how does it work? Do I combine the matrix that I find on GTEx with the counts matrix of my own dataset? Or do I create two separate objects? Or do I pass it to a separate argument in the CreateInfercnvObject function? And also, which file do I choose from the GTEx datasets?
2) Do I need to know exactly what cell types all of my cells are? Can I just annotate them by patient (ie I will have two columns for my annotations_file argument with the first column being cell ID and the second column being patient ID)

I know this is a lot of questions, but I am a little bit lost :(

Thank you in advance for your help :)

**Comment by GeorgescuC** [comment]
Hi @yana123668 ,

1. If you have two matrices, you should combine them. Since the "raw_counts_matrix" argument accepts either a file or a matrix, you can either read both matrices in R and combine them there before using them with infercnv, or combine the two matrix files through another method and then use the resulting file as input for infercnv.
As for using GTEx data, we currently don't have good support for that method, but they have a "coming soon" section for single cell data, so once that is released, we may look back at it.

2. Ideally, you want to have reference cells (healthy cells) for all the cell types you also have in your tumour samples so that you can make sure CNV signal is actually due to CNVs and not to cell type differences from unaccounted profiles. One thing to note though is that the actual name or id of the cell type does not matter for infercnv, the only thing that matters is the presence of references of the same cell types to compare to. Regardless of their names, infercnv automatically looks for the reference that looks the closest to compare them to.
Having cell types preclustered in the references also means you do not have to ask infercnv to split the references based on the hclust if you have different cell type profiles.
To identify cell types based on marker genes, you can for example use Seurat in R or Scanpy in Python.

Regards,
Christophe.
