### ISSUE TITLE
Subcluster name formatting

### ISSUE THREAD

**Issue by iheartfoosball** [broadinstitute/infercnv#337]
Hi team,

Thanks for the great package!

I am attempting to generate phylogenetic trees with subclustering info using [Uphyloplot2](https://github.com/harbourlab/uphyloplot2), but it looks like my .cell_groupings file has a different subcluster nomenclature. Is there a previous version of infercnv that generated names similar to the ones in the uphyloplot2 tutorial (e.g. "all_observations.all_observations.1.1.1.1")? My subcluster names are "all_observations.all_observations_s1" and so on. I used the tutorial files as they suggested but still have the s1, s2, etc. names. Tried looking at the previous versions of the functions involved in subclustering but couldn't find any that would generate the 1.1.1 type names.

Any thoughts appreciated - thanks!

Best,
Kaleab

**Comment by iheartfoosball** [comment]
Hmm, seems like the random trees method produces cluster names of the 1.1.1 variety. Is this exclusivity intentional?

**Comment by GeorgescuC** [comment]
Hi @iheartfoosball ,

To generate names in the 1.1.1 variety, you need to use the random_trees method for subclustering yes. This is because this method builds one hclust/phylogeny and then tests which branchings the tree should be split at, so there is a clear phylogeny to generate the names as paths based on the binary division of the tree.
In the newest version of infercnv, the default subclustering method uses the Leiden algorithm which is a community detection algorithm in a network, in this case a k nearest neighbor graph. This means there is no phylogeny directly involved in generating the clustering. We decided to add this method and make it the default because the random trees method scales poorly in run time with larger datasets, which people are starting to generate more often (and with more and more cells).

Regards,
Christophe.

**Comment by iheartfoosball** [comment]
I see, thank you!
