### ISSUE TITLE
Option to reference each observation against two reference groups

### ISSUE THREAD

**Issue by marlaherr** [broadinstitute/infercnv#343]
Hi there,

Thanks for sharing this great tool! I've been using it for a while now and am excited about the results.

I am using an integrated dataset with 6 tumor samples and 3 reference samples. In my previous runs, I simply selected the reference samples (either by sample or by cell types) as references. The tumor is most probably of epithelial origin and in the resulting heat map (attached below) I also see the most CNVs in epithelial cell groups. However, I also see some CNVs in immune and other cell types that should not be tumorigenic. Now I am wondering if these "CNVs" are confounders due to sample preparation and/or if they represent germ line CNVs. Is it possible to normalise my epithelial tumor population against these non-epithelial cells from the tumor samples as well (for example in a second referencing run)? 

I am very grateful for any suggestions. Thank you in advance.

Best wishes

![image](https://user-images.githubusercontent.com/83457321/125309110-c4d30b00-e331-11eb-916c-446ac28765dd.png)

**Comment by GeorgescuC** [comment]
Hi @marlaherr ,

If you want to add more references, you can do it directly in the same run by adding them to the ref_group_names option, infercnv will take the reference that is closest to each tumor sample. But before doing so, I would check the following too:
- Seeing as these are the HMM results, do you see the same effect in the residual expression figure (inferncnv.png) as a control that the issue is not with the prediction step?
- In this case the issue may be due to having too many different cell types in the same run. I would try running infercnv on each normal vs the matching tumor cell type (combining all the epithelial clusters together should work). Part of the analysis involves selecting which genes are expressed above the filtering threshold, but if you combine too many different cell types, you risk removing genes on the lower expression levels that are specific to certain cell types and keeping genes that are not expressed in other cell types.

Regards,
Christophe.
