### ISSUE TITLE
Identify malignant cell

### ISSUE THREAD

**Issue by zym826** [broadinstitute/infercnv#345]
Thanks a lot for making this package.
I don't know how to identify malignant cell,I extract epithelial cell ,and then I use normal epithelial cell to references.
![image](https://user-images.githubusercontent.com/82082831/126032079-a6e7672f-e703-4ae8-8029-2c0bc1075ac9.png)
In this picture, we can't tell directly whether the cell is malignant or not,so what method I can use to identify malignant cells.

**Comment by ptdtan** [comment]
May I ask where did you get the normal epithelial cells? Because I see a mixed population in your normal reference.

**Comment by zym826** [comment]
I download datas from GEO,there are normal patient  like this:
![image](https://user-images.githubusercontent.com/82082831/127475600-00a38e81-a93d-40bc-acdb-c7edfe7749dd.png)
and this :
![image](https://user-images.githubusercontent.com/82082831/127475748-dffee1f3-de30-42b1-aa19-e78f788ea941.png)
I identify epithelial cells from normal patients

**Comment by GeorgescuC** [comment]
Hi @zym826 ,

As ptdtan mentioned, your reference population is composed of multiple cell types/profiles. For infercnv to properly zero their signal, you should subdivide that population. In your case there seem to be about 6 different profiles/types, so the easiest solution would be to try adding the option `num_ref_groups=6` in run() and see if that is enough to remove the signal from your references. If that works, then the signal you see in the tumor samples should be correct.
If that doesn't work (either because there are a different number of cell types or they are not properly split with this method), you can try to run something like a Leiden clustering on your references and add the cluster id to the annotation names of the references, then provide all of them as references at the time of infercnv object creation.

Regards,
Christophe.

**Comment by apal6** [comment]
Hi Christophe,

I wonder is there's a way to define copy number alterations using some threshold than just looking at output plots. I have a normal population in malignant cluster and would be helpful in identifying and defining that as true normal than some technical error. 

Best,
Aastha
