### ISSUE TITLE
How to deal with batch effect?

### ISSUE THREAD

**Issue by fangfang0906** [broadinstitute/infercnv#346]
Thanks for developing this tool!  It's really cool!
I have the same sample with different sequencing protocols (3 prime and 5 prime). After running infercnv, the heatmap looked very similar except the 5 prime sample exhibited a strong chr22p gain. Is it artificial or true biology? Is infercnv robust to batch effect?

**Comment by GeorgescuC** [comment]
Hi @fangfan0906 ,

We have not experimented with mixing difference sequencing protocols within one experiment/run, but you can give a try to methods for dataset integration available in other tools as preprocessing.

For your specific run, is only 3 prime data set as reference?

Regards,
Christophe.

**Comment by fangfang0906** [comment]
Hi @GeorgescuC, 

Thanks for the reply. Yes, only 3 prime dataset was set as reference because I don't fond appropriate 5 prime reference data. I've tried some integration methods and one of them returns corrected lognormalized/scaled data. Does that work for infecnv? or it only accepts raw count matrix as input?

**Comment by GeorgescuC** [comment]
Hi @fangfang0906 ,

Infercnv uses raw counts because it does its own normalization and scaling. What you can however try is taking the code of the run() function (in inferCNV_ops.R) and edit it. What you will need to do is disable/skip steps 2 (filtering), 3 (normalization) and 4 (log transform). Depending on whether you want to run the HMM or not, the way to do it will be a bit different. 
If you do not intend to use the HMM, you can simply take advantage of the reload mechanic and set the variable "skip_past=4" after the piece of code that normally sets it by looking at what files you have in your output folder (lines 397 to 459). This way the process should just start at step 5.
If you intend to use the HMM, you will have to comment out step 2 and 4 entirely, then for step 3, comment out everything except the lines in the `if (HMM...) {}` block. Reinstall the package after that, and you should be able to run things with your integrated data.

One thing to remember to do in both cases is to filter the genes with no expression or very low expression before running infercnv as you will have disabled that step (because infercnv expects raw counts for its filtering, not log transformed data).

Also, to make sure, is your log normalization in the form of log2(x+1)?

Regards,
Christophe.
