### ISSUE TITLE
Different inferCNV.png ouput with and without HMM arguments

### ISSUE THREAD

**Issue by yannk-lm** [broadinstitute/infercnv#366]
Hello,

Thank you for developping such a useful package.

I was trying different arguments in the infercnv::run function using exactly the same input (reference, observation, annotation file and gene order file) with inferCNV 1.8.0, when I stumbled upon something intriguing for a neophyte like myself. Of note, the observations are from the same patient.

This heatmap is the inferCNV.png generated by the function below :

![infercnv](https://user-images.githubusercontent.com/84862273/135653284-c88cf33c-e919-494e-bbfc-926a5e944de3.png)

infercnv::run(infercnv_obj,
out_dir= "infcnv_result"
cutoff=0.1, 
cluster_by_groups=F, 
plot_steps=F,
denoise=T,
no_prelim_plot=T,
plot_steps=F)

These heatmaps are the inferCNV.png and the infercnv.20_HMM_predHMMi6.*.png, generated by the function below  :

![infercnv](https://user-images.githubusercontent.com/84862273/135653715-e0e863f3-bfcc-4025-a485-87c011dc25ec.png)

![infercnv 20_HMM_predHMMi6 leiden hmm_mode-subclusters Pnorm_0 5 repr_intensities](https://user-images.githubusercontent.com/84862273/135653749-375543b3-5b5f-4e92-ba8e-78078bd5c3fc.png)

infercnv::run(infercnv_obj,
out_dir= "infcnv_result"
cutoff=0.1, 
cluster_by_groups=F, 
plot_steps=F,
denoise=T,
no_prelim_plot=T,
plot_steps=F,
HMM = T,
BayesMaxPNormal = 0.5,
analysis_mode = "subclusters",
tumor_subcluster_partition_method = "leiden",
leiden_resolution = 0.0001,
k_nn = 20)

This raise 2 questions:
1) What argument(s) in infercnv::run function made this difference of inferCNV.png happened?
2) Why both dendrogram seems (are?) identical?

Regards,
Yannick

**Comment by GeorgescuC** [comment]
Hi @yannk-lm ,

Looking at the 2 residual expression figures, it looks like the expression per cell are actually very similar, but the difference is in the ordering of the cells. If you look at the reference cells, they actually look identical.
I am not sure at this time what exactly the issue in the sorting is, because the dendrograms on the side are identical, yet the cells clearly do not look sorted the same way. There may be a bug in there, but there are some things to check first too.
- Did you maybe use the result object from the 1st run to do the 2nd run?
- Did you manually edit/combine fields from the objects?
- The "leiden_resolution" parameter you used is set to too low a value. The go-to initial value is 1, and it is defined as "A parameter value controlling the coarseness of the clustering. Higher values lead to more clusters." (taken from scanpy doc as R leiden also makes use of the same python leiden library). In your case, this extremely low value results in a single cluster (as can be seen in the HMM figure), however the hclust/sorting of the cells should still be done correctly within that one cluster, and end up looking like the first run.

One thing you can check is also what the `infercnv_obj@tumor_subclusters` look like in both cases. The `$hc` should be identical (besides the name of the group) if the dendrogram look alike, but it probably isn't in terms of order of cells. 

Regards,
Christophe.

**Comment by yannk-lm** [comment]
Hi @GeorgescuC 

Thank for your responding in such short notice.

To answer your questions:
1) I wiped my R environment and only loaded my expression matrix before the run
2) I didn't modify any of the objects
3) I used this resolution and k_nn because it did not produce any overclustering when I used them on UMAP. Your comment made me want to try infercnv::run with default parameters (resolution = 1 and k_nn = 30), which generated the following heatmaps :

![infercnv](https://user-images.githubusercontent.com/84862273/135725311-36e363f6-1ebe-4938-b2ec-783036973821.png)

![infercnv 20_HMM_predHMMi6 leiden hmm_mode-subclusters Pnorm_0 5 repr_intensities](https://user-images.githubusercontent.com/84862273/135725322-85329a1f-4b0b-429c-8c35-b73fcdfa26c4.png)

These results are consistent with the very first heatmap, so I guess the issue was the absence of clusters.

For your information, I had these warnings at the end of the run
In type.convert.default(X[[i]], ...) : 'as.is' should be specified by the caller; using TRUE

Finally, I plotted the two infercnv_obj@tumor_subclusters$hc$all_observations from the previous heatmap and their dendrograms were identicals.

Regards,
Yannick

**Comment by GeorgescuC** [comment]
Hi @yannk-lm ,

For the warnings, I have not been able to do anything about them because they were introduced with recent R changes in one of the dependencies. They seem to be a case of R wanting a more explicit conversion, but I have not been able to find any actual issue coming from it.
I think the reason why the dendrograms are identical although the cells are clearly not sorted the same might be that you used the same output directory, and only part of the information stored in the `@tumors_subclusters` slot is updated.

Regards,
Christophe.
