### ISSUE TITLE
The infercnv result does not contain the X chromosome 

### ISSUE THREAD

**Issue by Rui-Jing** [broadinstitute/infercnv#376]
Hi,
Thanks for developing this user-friendly tool. I have a question about the output of the infercnv.

The question is my output heatmap **without X chromosome**. The heatmap is shown below :
[
![87e8de3836c70eaef3a5bd72db363f8](https://user-images.githubusercontent.com/59251760/141940056-5f5d5366-9623-4489-b7d9-7ff0b70106f7.jpg)
](url)
The pixels are not clear, but it does lack the X chromosome.

The X chromosome found in my **gene_order_file** files.

My code is :
`**infercnv_obj = CreateInfercnvObject(
  raw_counts_matrix=counts_p121_2,
  annotations_file="/home/pc/p121_2_annotation.txt",
  delim="\t",
  gene_order_file="/home/zfzf/mm_geneOrderingFile.txt",
  ref_group_names=c("P121_2_Oligodendrocytes","P121_2_Macrophages","P121_2_Microglia-1",
                    "P121_2_Proliferation-related immune cells","P121_2_Microglia-2","P121_2_Ependymal cells"))**

**infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1, 
                             out_dir="/home/pc/infercnv/",
                             cluster_by_groups=FALSE, 
                             analysis_mode="subclusters", 
                             denoise=TRUE,
                             HMM=TRUE,
                             HMM_type = "i6",
                             num_threads=4)**`

when i grep X in my gene_order_file ,the output is below:
[
![1637048520(1)](https://user-images.githubusercontent.com/59251760/141942006-0028dfbe-b4d2-44cf-a7e1-8c4de6f42b10.png)
](url)
I sincerely hope to get your help. Thanks.

**Comment by GeorgescuC** [comment]
Hi @Rui-Jing ,

There is an option to filter out certain chromosomes, but by default it is set to "c('chrX', 'chrY', 'chrM')", which is not the naming you are using. In this case the issue seems to only be with the labels on the plot. Your figure has "MT" near the end, but if you look closely, there are actually 2 chromosome separators in that spot. R does not allow for overlapping labels, so the 2nd label that should be there, in this case "X", is not displayed because the "MT" is so small that there is no space to display both labels.

Regards,
Christophe.
