### ISSUE TITLE
Keep sample names in output CNV plot

### ISSUE THREAD

**Issue by komalsrathi** [broadinstitute/infercnv#38]
Hi,

Is there a way to keep the sample names in the rows of the output CNV plot? 

For e.g. here the rows don't have any annotation so I can't figure out which row belongs to what sample.  
[infercnv.pdf](https://github.com/broadinstitute/inferCNV/files/2288440/infercnv.pdf)

Thanks
Komal``

**Comment by GeorgescuC** [comment]
Hi @komalsrathi 

On the stable release, there is no option to have the sample names directly next to the rows as they would quickly be too little space for each, but you can find in the output folder two files. 
The first is "observations_dendrogram.txt" that contains the dendrogram of the samples clustering, from bottom to top, as a newick string. 
The second is "observation_groupings.txt" that contains the ordered samples and the color they have based on the group splitting if "--obs_groups" is set to anything >= 2.

If you are interested, we also have a development branch that has new features you can try. It adds information about sample annotation type on the plot and legend, allows to have samples be clustered by type/patient using annotations, and generates a file to be loaded with the interactive viewer NGCHM (which is probably be the most powerful solution for what you are interested in). If you would like to try it, I can provide you with updated instructions on how to install and use it (they are currently not live on the wiki).

Best,
Christophe.

**Comment by komalsrathi** [comment]
If I have three observation groups and I specify `--obs_groups 3`, then where do I actually specify what columns belong to what group?

**Comment by GeorgescuC** [comment]
You need to have at least one reference/control sample for infercnv to compare the observations to.

On the main branch, "--obs_groups" splits the samples based on the hierarchical clustering only.

On the development branch, the "--ref_groups" option has been replaced by one to specify a file that contains a line for each sample on which you specify what group of samples it is part of (for both references and observations). Samples are then marked on the plot based on this grouping.

**Comment by komalsrathi** [comment]
What is the purpose of the reference group and can I use one of my observation groups as reference groups?

**Comment by GeorgescuC** [comment]
The purpose of the reference group is to define the base expression level of the genes at normal Copy Number (2 in human), so infercnv can analyze relative expression changes and identify gain and losses of copies.
You can define your group1 as reference, but you have to be careful that if that group has, for example, 3 copies of a chromosome, all groups that have the regular 2 copies will appear to have a loss of a copy. (the case where your reference has a loss of copy can also happen). If you have 2 groups that are tumor samples and 1 that is a healthy sample, this last one should be the reference.

As for how to run infercnv with a reference group, I am going to give you instructions to use the branch currently in active development because it also adds the information your are looking for in your other thread (https://github.com/broadinstitute/inferCNV/issues/39). This branch will get a few more changes done in the coming days before we release it as the main version.

1) Create a new tab separated file (that I will refer to as "annotation_file" in the command to run) with the following format (you will need to indicate the actual names of your samples) :
>sample_1    group1
>sample_2    group1
>sample_3    group1
>sample_4    group1
>sample_5    group2
>sample_6    group3
>sample_7    group2
>sample_8    group3
>sample_9    group2
>sample_10    group3
>sample_11    group3
>sample_12    group3

2) Download the source code of the "bioc" branch from the following link :
>https://github.com/broadinstitute/inferCNV/archive/bioc.zip

3) Extract the source code.

4) Run an R session from the extracted folder and type the following to install the library : 
>install.packages("./", repos=NULL, type="source", INSTALL_opts = "--with-keep.source")

5) Load the installed library :
>library(infercnv)

6) Run your analysis with the following command where you need to update the paths to the input files and the output path :
>infercnv::infercnv(x="expression_matrix_file" ,annotations="annotation_file", gene_order="gencode_v19_gene_pos.txt", cutoff=1, noise_filter=0.2, output_dir="output_path", name_ref_groups="group1", output_format="png", cluster_by_group=FALSE)

Let me know if you have any issues with running this.
