### ISSUE TITLE
The proportion_scaled_cnv of all cells in observation group were identical??

### ISSUE THREAD

**Issue by fengwei-li** [broadinstitute/infercnv#380]
Hi,
I did the inforcnv calculation, however, the results I got indicated that The proportion_scaled_cnv of all cells(in observation group) were identical. Moreover, for a particular chromosome, only one score(or 0) was  given, which was not reasonable(cnv.txt). I'm very very confused.
```
infercnv_obj <- CreateInfercnvObject(raw_counts_matrix = count,
                                     annotations_file = '6.cell_group.txt',
                                     delim="\t",
                                     gene_order_file = '6.gene_order.txt',
                                     ref_group_names = "Fibroblasts")
n <- 'inferCNV_20211121'
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1, 
                             out_dir=n, 
                             cluster_by_groups=F,
                             hclust_method="ward.D2",
                             HMM=T,
                             denoise = T,
                             num_threads = 4)
chol_CAF_cnv = infercnv::add_to_seurat(
  infercnv_output_path="G:/Analysis_data/Step6/inferCNV_20211121/", seurat_obj=chol_CAF,top_n=10)
```
[cnv.txt](https://github.com/broadinstitute/infercnv/files/7607404/cnv.txt)
![infercnv](https://user-images.githubusercontent.com/54225799/143552473-1eff5dce-3c78-4030-9041-7ae75c13ab29.png)

**Comment by GeorgescuC** [comment]
Hi @fengwei-li ,

The results from add_to_seurat are based on the HMM predictions. Since you did not use the subclustering option, there is a single cluster containing all your observation cells, and the whole cluster receives a single set of predictions, as you can check if you look at the HMM figures. Seeing your cells are clearly from multiple clonal populations, You should use the `analysis_mode="subclusters"` option to get meaningful HMM predictions and metric export from add_to_seurat.

Regards,
Christophe.
