### ISSUE TITLE
Error after installing version 1.11.1

### ISSUE THREAD

**Issue by Sa753** [broadinstitute/infercnv#381]
Dear team,

I was running version 1.9 and updated it to the new version 1.11.1 but now I am getting an error at step 6

I used the following code

count_matrix = cfcf@assays$RNA@counts
meta <- as.data.frame(cfcf@active.ident)
colnames(meta) <- 'cluster'
options(scipen = 100) 
infercnv_obj_m = CreateInfercnvObject(raw_counts_matrix=count_matrix,
                                    annotations_file=meta,
                                    gene_order_file= '~/ncbi_mm10.txt',
                                    ref_group_names=c('11', '18')) 

infercnv_obj_m = infercnv::run(infercnv_obj_m,
                             cutoff=0.1,  # use 1 for smart-seq, 0.1 for 10x-genomics
                             out_dir="dir_infercnv",  # dir is auto-created for storing outputs
                             cluster_by_groups=F,   # cluster
                             denoise=T, HMM = T, analysis_mode = 'subclusters' , num_ref_groups = 2, num_threads = 20)

The output is 

INFO [2021-12-02 22:57:26] ::process_data:Start
INFO [2021-12-02 22:57:26] Creating output path mouse_infercnv
INFO [2021-12-02 22:57:26] Checking for saved results.
INFO [2021-12-02 22:57:26] 

	STEP 1: incoming data

INFO [2021-12-02 22:57:51] 

	STEP 02: Removing lowly expressed genes

INFO [2021-12-02 22:57:51] ::above_min_mean_expr_cutoff:Start
INFO [2021-12-02 22:57:52] Removing 14250 genes from matrix as below mean expr threshold: 0.1
INFO [2021-12-02 22:57:53] validating infercnv_obj
INFO [2021-12-02 22:57:53] There are 9163 genes and 5891 cells remaining in the expr matrix.
INFO [2021-12-02 22:57:57] no genes removed due to min cells/gene filter
INFO [2021-12-02 22:58:22] 

	STEP 03: normalization by sequencing depth

INFO [2021-12-02 22:58:22] normalizing counts matrix by depth
INFO [2021-12-02 22:58:28] Computed total sum normalization factor as median libsize: 11866.000000
INFO [2021-12-02 22:58:53] 

	STEP 04: log transformation of data

INFO [2021-12-02 22:58:53] transforming log2xplus1()
INFO [2021-12-02 22:59:20] 

	STEP 06: splitting reference data into 1 clusters

INFO [2021-12-02 22:59:20] ::split_references:Start
Error in parallelDist(t(ref_expr_matrix), threads = infercnv.env$GLOBAL_NUM_THREADS) : 
  x must be a matrix or a list of matrices.

Could you please kindly help?

Thanks

**Comment by Sa753** [comment]
Are you able to help please?

**Comment by GeorgescuC** [comment]
Hi @Sa753 ,

It seems like `parallelDist`, that was added to 1.11.1 to speed things up does not handle sparse matrices. This only seems to be an issue when using the option to split references in a given number of groups, as in post-smoothing steps the matrix is always dense. I have pushed a fix to the master branch, so if you update your local install using github, things should work.

And just to make sure the run does what you intended, using the `num_ref_groups = 2` option means all cells from all the provided reference annotation groups `ref_group_names=c('11', '18')` will be split according to `cutree` on an `hclust` in 2, not to the annotation themselves.

Best,
Christophe.

**Comment by Sa753** [comment]
Hi Christophe,
Thanks for getting back to me. 

I am sorry, I don't fully understand the 2nd paragraph of your reply. Basically, I put 2 reference groups because I have cancer cells that are undergoing EMT so I put a reference of normal cells from epithelial and mesenchymal origins . is that correct to do?.

Regarding the error, you are absolutely correct, it happened when I put 'num_ref_groups = 2 ' argument
, if I deleted it , it skips from step 4 to step 8 and no error (i.e, bypass step 6).

I reinstalled the package from 

devtools::install_github("broadinstitute/infercnv") 

but the error is still the same if I put num_ref_group. Is that the correct place to get the updated version?.

Thanks

**Comment by GeorgescuC** [comment]
Hi @Sa753 , 

Regarding the reference groups the way it works is as follow:
You provide the input annotations to know which cells are "together", and from those annotations you can set some of them to be used as references with "ref_group_names=c("11", "18")". If you only do this, by default cells with the "11" annotation will form 1 group of references, and cells with the "18" annotation will form a 2nd group of references (and so forth if you have more than 2 groups).
Now if you add the "num_ref_groups=2" option, all cells annotated "11" and "18" will be put together in a single group to run an hclust on. The resulting hclust is then split in 2 (the value of the option) using "cutree" to give you 2 reference groups composed only of cells annotated "11" and "18", but where each group can contain cells annotated with either.
An example use of this option would be when your cells are annotated by patient but not by cell type. You could then provide the healthy group(s) as a reference but have it be split in a number of groups to separate the cell types.

For the step being skipped, that is normal. The steps retain their numbering whether optional ones are run or not in order to make logs more consistent. Since the optional process of redefining reference clusters I described above that is step 6 is not being run, steps skip from 4 to 8 (5 and 7 are also optional).

Regarding the error, could you please let me know what running `is(infercnv_obj@expr.data)` on the newly created infercnv object returns?

Regards,
Christophe.

**Comment by Sa753** [comment]
Hi Chris,
This is the output of this. 

> is(infercnv_obj_h@expr.data)
 [1] "dgCMatrix"      "CsparseMatrix"  "dsparseMatrix"  "generalMatrix" 
 [5] "dCsparseMatrix" "AnyMatrix"      "xgCMatrix"      "dMatrix"       
 [9] "sparseMatrix"   "compMatrix"     "Matrix"         "xMatrix"       
[13] "mMatrix"        "replValueSp"  

Please advise
Thanks

**Comment by Sa753** [comment]
Dear Chris,

This issue is now resolved. Like you said, it can't handle sparse matrix but when I made th input as matrix , it worked. 
Thank you
