### ISSUE TITLE
FBI observation

### ISSUE THREAD

**Issue by Sa753** [broadinstitute/infercnv#384]
Dear Christophe,

Is it possible to study foldback inversion on single cell RNAseq of cancer cells using infercnv?.

Thanks

**Comment by Sa753** [comment]
Dear Christophe,

Is there any chance you can help with the above query please?

Thanks

**Comment by GeorgescuC** [comment]
Hi @Sa753 ,

I don't think it is possible to study specifically foldback inversion using only infercnv. This tool allows to identify regions that are duplicated, but because we are using RNAseq read counts per gene, we have no information about the relative organization of the copies or even phasing.

Regards,
Christophe.
