### ISSUE TITLE
Subclustering samples based on predefined groups

### ISSUE THREAD

**Issue by angkoomin** [broadinstitute/infercnv#385]
Hi there, 

I was wondering how can I divide my "observation (cells)" based on groups. I have 2 groups (named as "Zones") which is PZ and TZ. How do I divide them per group 1st before applying the cluster_by_groups? 

I'm basically trying to manually choose my group rather than use the k_obs_group function.

![image](https://user-images.githubusercontent.com/61758903/146470218-d91f9285-078f-4b6c-b533-dd0ce3ae8fe1.png)

This is my code:
out_dir = 'inferCNVresult_new_Dave.subset'
infercnv_obj_default = infercnv::run(
    infercnv_object_own.subset ,
    cutoff=0.1, # cutoff=1 works well for Smart-seq2, and cutoff=0.1 works well for 10x Genomics
    out_dir=out_dir,
    cluster_by_groups=TRUE, 
    plot_steps=FALSE, 
    denoise=TRUE,
    HMM=FALSE,
    no_prelim_plot=TRUE,
    png_res=60,
    num_threads = 6
)

Thanks,
Amin

**Comment by GeorgescuC** [comment]
Hi @angkoomin ,

If you simply want to have 2 observation groups, one "PZ" and one "TZ", the easiest solution would be to change your annotations names for the non-reference cells to something like "obs_PZ" and "obs_TZ". 

If you want to keep the multiple "PZ" and "TZ" groups you have but have them in order, there are 2 options:
- update infercnv to the latest commit on the master branch on which I added a sort to the annotation groups names, then change your annotation names to have the "PZ" or "TZ" at the beginning the name so they are both grouped. Then rerun infercnv in a new folder (otherwise the old ordering from the backup will be loaded).
- manually change the order of the annotation groups in the `infercnv_obj@observation_grouped_cell_indices` slot. You don't need to edit the content (list of cell indices) of the each annotation group, just their relative order to group them by "PZ" and "TZ".

Regards,
Christophe.
