### ISSUE TITLE
Question about result interpretation

### ISSUE THREAD

**Issue by TChen0730** [broadinstitute/infercnv#389]
Thanks a lot for developing the powerful tool.

I ran infercnv on 500 human cells including both case and control. I found only 806 genes pass the filter (I used the default value for min_cells_per_gene). My question is whether the results would be reliable if they were inferred only based on hundreds of genes? 

Thank you so much!

**Comment by GeorgescuC** [comment]
Hi @TChen0730 ,

What type of sequencing was used to generate your data? It sounds like the "cutoff" option is set too high for your data. The default is 1, which works well for SmartSeq2, but if you have 10X data, you should set it to 0.1 .

Regards,
Christophe.

**Comment by TChen0730** [comment]
The data was generated by 10x platform, and the cutoff I used is 0.1. The dataset is a published dataset generated 3 years ago, the captured genes were not as much as the recent datasets. Thus, I am wondering whether I can trust the results inferred based on hundreds of genes? Another question is: How many genes passing the filter can be regarded as acceptable to generate reliable results? Thank you!

**Comment by GeorgescuC** [comment]
Hi @TChen0730 ,

Are the values in the matrix raw counts? I would plot the sorted sum of reads per cell and average reads per gene to have an overview of the depth of sequencing and a pointer for what cutoff you might need.
With 806 genes, the average number of genes kept per chromosome is barely over 35 which is very low. Because the default (weighted) smoothing window is 101 genes, you would want at least that many genes on average. More would be better though since few genes means the smoothing is done over long stretches of the chromosome of which most has no information, making it hard to be sure where the breakpoint of a CNV is.

Regards,
Christophe.

Regards,
Christophe.

**Comment by TChen0730** [comment]
Thanks a lot for the explanation. It is very helpful!
