### ISSUE TITLE
how to extract cnv score and plot it on UMAP

### ISSUE THREAD

**Issue by xinmiaoyan** [broadinstitute/infercnv#393]
hello, nice tool. right now I would like to calculate cnv score for each cell and plot it on umap. I tired below method to calculate the cnv score, but failed to plot it on umap since the cnv score are continuous, not discrete. 
![image](https://user-images.githubusercontent.com/83053884/152888714-51bd936c-4def-4ccb-8167-132176518939.png)
I also tried this https://github.com/broadinstitute/inferCNV/wiki/Extracting-features, but there're no cnv score in the feature list.
appreciate it if you could help.

**Comment by GeorgescuC** [comment]
Hi @xinmiaoyan ,

The feature lists extracted do not have "scores" per say because they are based on the HMM predictions that give you specific CNV fold change levels. The features give you values such as the proportion [0;1] of each cell's genes that are part of CNVs, and some of them are specific to gain or loss, while others combine both. There are also features that are weighted by whether the CNV is a single or double copy gain/loss, while others only check whether a CNV is present or not.
You should also be able to plot continuous scores on a umap with the `ggplot2::scale_colour_gradient` method as shown on the documentation page you linked.

The CNV estimations mentioned in the paragraphs you sent are based on the residual expression. This you can find those either directly in the infercnv object in the `infercnv_obj@expr.data` slot, or can read them from the `infercnv.observations.txt` and `infercnv.references.txt` tables.

Regards,
Christophe.
