### ISSUE TITLE
STEP 13 problem detected with infercnv_obj

### ISSUE THREAD

**Issue by andynkili** [broadinstitute/infercnv#399]
I have created my inferCNV object with:
```

infercnv_obj = CreateInfercnvObject(raw_counts_matrix=mydata@assays$RNA@counts,
                                    annotations_file='Oligo_cluster_annotation.tsv',
                                    delim="\t",
                                    gene_order_file="GRCh38_gene_position.txt",
                                    ref_group_names=c("Microglia/Macrophage"))
```
and have run:
```
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1,  # use 1 for smart-seq, 0.1 for 10x-genomics
                             out_dir="oligoNoMHC_inferCNV_refMacro_window401_modeSubcluster",
                             num_threads = 18,window_length = 401,
                             HMM_type = 'i6',BayesMaxPNormal = 0.5,
                             plot_steps = F, plot_probabilities = F, save_rds = F, save_final_rds = T,remove_genes_at_chr_ends = T,no_prelim_plot = T,
                             cluster_by_groups=T,   # cluster
                             denoise=T,
                             analysis_mode = "subclusters",
                             HMM=T)

```

but I got the following error:
```
	STEP 13: removing genes at chr ends

INFO [2022-03-01 09:46:10] validating infercnv_obj
INFO [2022-03-01 09:46:10] ::process_data:Remove genes at chr ends, new dimensions (r,c) = 1134,29852 Total=5570.96814227099 Min=-0.333365817712969 Max=2.18325628154318.
INFO [2022-03-01 09:46:10] -mirroring for hspike
INFO [2022-03-01 09:46:10] validating infercnv_obj
ERROR [2022-03-01 09:46:10] hmm.... rownames(infercnv_obj@expr.data != rownames(infercnv_obj@gene_order))
Error in validate_infercnv_obj(infercnv_obj) : 
  Problem detected w/ infercnv_obj
```

However I checked:
```
identical(rownames(infercnv_obj@expr.data),rownames(infercnv_obj@gene_order))
[1] TRUE
```

So what could be wrong with my object?

**Comment by GeorgescuC** [comment]
Hi @andynkili ,

The error seems to occur in the hidden spike data, which is generated to calibrate the HMM, and stored in `infercnv_obj@.hspike` . You could try `identical(rownames(infercnv_obj@.hspike@expr.data),rownames(infercnv_obj@.hspike@gene_order))` to check that data. Interestingly, you have set the smoothing window to 401 genes, while the simulated chromosomes in the hspike are 400 genes long, so the issue might be related to that.

An object called `broken.infercnv_obj` should have been generated when the error occured, could you share it privately? (since the error is the hspike, this object should only contain the simulated data)

Regards,
Christophe.

**Comment by andynkili** [comment]
Hi @GeorgescuC,

It turns out that I was running an old version of infercnv.
Upgrading the tool version (1.1 -> 1.8.1) solved the issue.
I don't think the windows size was causing trouble as it is working just fine after the update even with window size over 400 genes.

Thank you for taking time to reply,
Andy

**Comment by xiangmingcai** [comment]
Hi,
I had the same error. However, my problem comes from the wrong subpopulation names I gave inferCNV.
This one has error:
```
infercnv_obj = CreateInfercnvObject(raw_counts_matrix=counts,
                                      annotations_file=anno,
                                      delim="\t",
                                      gene_order_file=gene_order,
                                      ref_group_names=c(1,2,5,6,8,10,12,14,16,18,20)) 
```

This one is ok:
```

infercnv_obj = CreateInfercnvObject(raw_counts_matrix=counts,
                                      annotations_file=anno,
                                      delim="\t",
                                      gene_order_file=gene_order,
                                      ref_group_names=c("1","2","5","6","8","10","12","14","16","18","20")) 
```

**Comment by xiangmingcai** [comment]
Hi,
I had the same error. However, my problem comes from the wrong subpopulation names I gave inferCNV.
This one has error:
```
infercnv_obj = CreateInfercnvObject(raw_counts_matrix=counts,
                                      annotations_file=anno,
                                      delim="\t",
                                      gene_order_file=gene_order,
                                      ref_group_names=c(1,2,5,6,8,10,12,14,16,18,20)) 
```

This one is ok:
```

infercnv_obj = CreateInfercnvObject(raw_counts_matrix=counts,
                                      annotations_file=anno,
                                      delim="\t",
                                      gene_order_file=gene_order,
                                      ref_group_names=c("1","2","5","6","8","10","12","14","16","18","20")) 
```

**Comment by willow0077** [comment]
Hi, I had the same error.
`
ERROR [2024-04-01 10:37:06] hmm.... rownames(infercnv_obj@expr.data != rownames(infercnv_obj@gene_order))
ERROR [2024-04-01 10:24:54] The following genes are in @gene_order and not infercnv_obj@expr.data: gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,gene_9,gene_10,gene_11,gene_12,gene_13,gene_14,gene_15,gene_16...
Error in validate_infercnv_obj(.hspike) :  Problem detected w/ infercnv_obj
`
But the issues cannot be fixed by using updating 'infercnv' or correct subpopulation names.
`
> 'gene_1' %in% rownames(infercnv_obj@gene_order)
[1] FALSE
> identical(rownames(infercnv_obj@expr.data),rownames(infercnv_obj@gene_order))
[1] TRUE
`
`
> packageVersion('infercnv')
[1] ‘1.18.1’
`
`
infercnv_obj = CreateInfercnvObject(raw_counts_matrix = mtx,
                                    annotations_file = celltype,
                                    gene_order_file= gtf,
                                    ref_group_names=c("3","6"))
`
