### ISSUE TITLE
InferCNV for HMM cell mode

### ISSUE THREAD

**Issue by cv55** [broadinstitute/infercnv#404]
Hello,

i am running InferCNV for my single cell data, using the cells analysis mode and HMM_report_by cell since I am just interested in seeing CNVs at the single cell level. I do not have cancer data so I am using the mean of all cells as reference. 
I am currently facing two issues:

1) The tool crashes when I use many cells as input (>5000). is there a way to alleviate this issue?
2) In the Bayes output folder, when HMM is called for each cell, all CNVs have almost the exact probability of being true CNVs. This probability ranges between 0.855 and 0.865. There I would expect to see a more normal distribution. Do you have an intuition on what could be causing this?
![infercnv NormalProbabilities PostFiltering](https://user-images.githubusercontent.com/18632504/159889197-47227e92-1c6a-46b2-b2b7-06273c4a6c61.png)

**Comment by GeorgescuC** [comment]
Hi @cv55 ,

1. Do you encounter any error, or does the process just die/get killed?
2. HMM predictions done over single cells exists as an option, but you should most likely never use it. The signal in a single cell is too noisy to be able to accurately determine if a CNV is real or noise, or its accurate boundaries. With only a single cell, there is very little data for the Bayesian network to run on too.
In all likelihood, the best thing to do would be to run the HMM in subclusters mode, so that clones can be identified and grouped together for an overall HMM prediction. You will still be able to report the results at the cell level, or look at the subclusters contents.

Since you are not using references, please also be careful that any CNV signal could be the opposite of the real CNV but on the normal cells, depending on your mix of normal/malignant cells.

Regards,
Christophe.

**Comment by mariaZig** [comment]
Hello, 

I'm opening this issue again because I have a relevant question. Please let me know if you prefer to create a new issue from scratch.

You say that we can still be able to report the results at the single cell level if we run the HMM in subcluster mode. 

I need to work with data similar to the content of the file ".....subclusters.Pnorm_0.5.pred_cnv_regions.dat" but having the reported CNVs (i.e., state/chr/start/end) for each single-cell independently. 

Is this possible? 

Thanks in Advance!
