### ISSUE TITLE
Error step 6

### ISSUE THREAD

**Issue by Sa753** [broadinstitute/infercnv#415]
Dear Chris,

I am running infercnv on docker and getting this error.

	STEP 06: splitting reference data into 2 clusters

INFO [2022-04-29 21:38:33] ::split_references:Start
Error in parallelDist(t(ref_expr_matrix), threads = infercnv.env$GLOBAL_NUM_THREADS) : 
  x must be a matrix or a list of matrices.

I also have the same error when running on my local machine. However, I don't get this error if I put ref_group_names=NULL. 

Could you pplease help?

Thanks

**Comment by GeorgescuC** [comment]
Hi @Sa753 ,

Which version are you running locally, and which version of the docker image are you using? I think the issue you are encountering should have been fixed in version 1.11.2 :
`+ Add conversion of expression data in sparse matrix format to dense matrix when splitting references in n groups as parallelDist does not handle them.`

The docker image may be slightly outdated, but I will be generating a new image soon as the new version of R and BioConductor just released. Updating your local version should however work directly.

Regards,
Christophe.

**Comment by naddoun** [comment]
Hi, I'm having the same error. my version of infercnv is 1.13.0, I was wondering if you could clarify any other causes of this error.

**Comment by naddoun** [comment]
Upon converting the input counts from a sparse to dense matrix using as.matrix(), the problem was solved.
