### ISSUE TITLE
Error in rasterImage(as.raster(zc), min(x), min(y), max(x), max(y), interpolate = FALSE) :

### ISSUE THREAD

**Issue by xiangrong7** [broadinstitute/infercnv#418]
Thanks for the great tool. But I have met an error. I have a large data about 10w cells. So it runs too much time and assumes much memory. 
But when I ran 'STEP 18: Run Bayesian Network Model on HMM predicted CNV's', the error occurred:
```bash
Attaching SeuratObject
Error in rasterImage(as.raster(zc), min(x), min(y), max(x), max(y), interpolate = FALSE) :
  cannot allocate memory block of size 16777216 Tb
Calls: run ... heatmap.cnv -> image -> image.default -> rasterImage
Execution halted
```

It seems the heatmap was too large but STEP 18 was successful.
```bash
INFO [2022-05-06 13:12:37] Creating the following Directory:  07.cluster_new_cnv_ggj/BayesNetOutput.HMMi6.hmm_mode-samples
INFO [2022-05-06 13:12:37] Initializing new MCM InferCNV Object.
INFO [2022-05-06 13:12:38] validating infercnv_obj
INFO [2022-05-06 13:12:38] Total CNV's:  1465
INFO [2022-05-06 13:12:38] Loading BUGS Model.
INFO [2022-05-06 13:12:55] Running Sampling Using Parallel with  6 Cores
INFO [2022-05-09 11:05:56] Obtaining probabilities post-sampling
INFO [2022-05-09 19:34:58] Gibbs sampling time:  4702.05432102283  Minutes
INFO [2022-05-09 22:39:57] ::plot_cnv:Start
INFO [2022-05-09 22:39:57] ::plot_cnv:Current data dimensions (r,c)=6868,101549 Total=208865107.410663 Min=0 Max=0.996447933019203.
INFO [2022-05-09 22:40:08] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2022-05-09 22:42:10] plot_cnv_observation:Start
INFO [2022-05-09 22:42:10] Observation data size: Cells= 85628 Genes= 6868
INFO [2022-05-09 22:43:59] plot_cnv_observation:Writing observation groupings/color.
INFO [2022-05-09 22:43:59] plot_cnv_observation:Done writing observation groupings/color.
INFO [2022-05-09 22:44:07] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2022-05-09 22:44:07] plot_cnv_observation:Done writing observation heatmap thresholds.
```
Which file should I read and continue drawing? and there is no need to re-run step18 because it needs too much time.

How can I go on the remaining steps without re-run step18?

**Comment by GeorgescuC** [comment]
Hi @xiangrong7 ,

For continuing the analysis, if you simply relaunch the same run, it should find the results saved at step 18 before attempting to plot and continue from the next step without rerunning step 18.

Regarding the plotting, this error has been reported a couple times in the past, but there never appears to be any reason why it should need 16Eb of memory. This is [an internal method of R's graphics](https://github.com/SurajGupta/r-source/blob/master/src/library/graphics/R/raster.R#L19) that simply [calls the C_raster method written in C](https://github.com/SurajGupta/r-source/blob/master/src/library/graphics/src/plot.c#L1816). From infercnv's side, we should just be calling image() to plot a matrix (in you case of 85628*6868 cells) which already fits within memory just fine. If you can share the data privately, I can take a look to make there isn't a bug in infercnv before calling image(), but there's no guarantee I'll be able to fix this issue.

To try to plot the figure again however, you can try manually running "plot_cnv" with the setting "useRaster=FALSE". The plot will take much longer to generate because it won't make use of rasterization, but it should avoid calling the method that errors out.

Regards,
Christophe.

**Comment by xiangrong7** [comment]
Thanks for your help! I solved the problem for the time being and the data is a little big and not very easy to share. Thanks again!

**Comment by Arshammik** [comment]
@xiangrong7, could you please share how you managed to solve the problem? I
Thanks!

**Comment by PPWEST522** [comment]
It's big matrix issue. I fixed it by cutting down the cell number.

**Comment by andynkili** [comment]
@GeorgescuC,

I am trying to deal with 100k cells and run into the same issue, however I tried to disable all plotting options  `plot_steps = F, plot_probabilities = F,no_prelim_plot = T,no_plot=T,useRaster = F` but still infercnv keeps trying to plot at STEP 15: 
```
INFO [2025-02-26 22:45:55] plot_cnv_observation:Writing observation groupings/color.
INFO [2025-02-26 22:45:56] plot_cnv_observation:Done writing observation groupings/color.
INFO [2025-02-26 22:45:59] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2025-02-26 22:45:59] plot_cnv_observation:Done writing observation heatmap thresholds.

```
And resulting in:
```
Error in rasterImage(as.raster(zc), min(x), min(y), max(x), max(y), interpolate = FALSE) :
  cannot allocate memory block of size 16777216 Tb
Calls: <Anonymous> ... heatmap.cnv -> image -> image.default -> rasterImage
```

Do you have any clues?

**Comment by andynkili** [comment]
Hi @GeorgescuC,

I tried "useRaster=False" (the plotting options in my previous comment), in vain.
Indeed "inspect_subclusters=F" disbable the plotting, it is now running step18.
After getting the final object, I will manually run "plot_cnv" and see how it goes.
Thank you for your prompt answer.

Have a great day,
Andy
