### ISSUE TITLE
Error message when clustering samples (step15, version 1.12.0)

### ISSUE THREAD

**Issue by chent5** [broadinstitute/infercnv#421]
Thanks for developing this very helpful package!

I got an error message in step 15 and last few lines in log file are shown as below:
```
INFO [2022-05-13 17:14:50] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2022-05-13 17:17:20] plot_cnv(): auto thresholding at: (0.870769 , 1.132526)
INFO [2022-05-13 17:17:23] plot_cnv_observation:Start
INFO [2022-05-13 17:17:23] Observation data size: Cells= 12000 Genes= 7217
INFO [2022-05-13 17:17:26] plot_cnv_observation:Writing observation groupings/color.
INFO [2022-05-13 17:17:26] plot_cnv_observation:Done writing observation groupings/color.
INFO [2022-05-13 17:17:26] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2022-05-13 17:17:26] plot_cnv_observation:Done writing observation heatmap thresholds.
Error in image.default(gene_position_breaks, seq_len(nr + 1), x, axes = FALSE,  : 
  'x' and 'y' values must be finite and non-missing
Calls: <Anonymous> ... .plot_cnv_observations -> heatmap.cnv -> image -> image.default
Execution halted
```

Here is the code I use:
```
infercnv_obj_default = infercnv::run(
  infercnv_obj,
  cutoff=0.1, 
  out_dir=out_dir,
  cluster_by_groups=TRUE, 
  plot_chr_scale = TRUE,
  plot_steps=FALSE,
  denoise=TRUE,
  HMM=TRUE
)
```

I have successfully run my data using inferCNV old version (v1.0.4). I tried the new version because I would like to try the new argument plot_chr_scale = T. Could you help to solve this issue? Thank you so much!

**Comment by GeorgescuC** [comment]
Hi @chent5 ,

Just to make sure, which version of infercnv are you now running? Some versions are dependent on newer version of R as well so you might not have the most recent version.
If you are on 1.12.0 or 1.13.0, could you share the data privately so I can take a look at what causes the issue?

Regards,
Christophe.

**Comment by chent5** [comment]
I use infercnv (v1.12.0) and R (4.2.0). I also found that if I do not use "plot_chr_scale = T", there is no error message. So it seems something wrong when I set "plot_chr_scale = T". Is this information helpful for trouble shooting?

**Comment by GeorgescuC** [comment]
Hi @chent5 ,

Yes this error points to an issue specific to using "plot_chr_scale=T" because we provide specific positions for gene columns to be plotted between based on their coordinates rather than equal column widths.
Could you try updating your install of infercnv to the current master branch? There is a small fix that didn't make it into the 1.12.0 and 1.13.0 versions but adds a check in case the midpoints of 2 genes end up being at the same coordinate, and if so shifts one of them by 1 so the coordinates remain strictly increasing as required by `image()`.

Regards,
Christophe.

**Comment by chent5** [comment]
Thanks a lot for your reply!

I re-installed the package using below code:
```
git clone https://github.com/broadinstitute/infercnv
cd infercnv
module load gcc/10.2.0 r/4.2.0
R
> install.packages("./", repos=NULL, type="source")
```
After that, I checked the version, which is v1.13.0, not the current master branch... I also tried v1.13.0, which still doesn't work.

Could you show me how to update my package to the current master branch? Thank you so much!

**Comment by GeorgescuC** [comment]
Hi @chent5 ,

If you did not change branch from the master you should have the change I mentioned, the version number has not been increased yet with these changes. Since you still have the issue, it seems like it is something different. Could you share with me the backup object from that step privately so I can debug the issue?

Regards,
Christophe.

**Comment by chent5** [comment]
Thanks so much for your help in advance. Could I have your email which you would like to receive the data?

**Comment by GeorgescuC** [comment]
Hi @chent5 ,

You can find my email in the [description file at line 6](https://github.com/broadinstitute/infercnv/blob/master/DESCRIPTION#L6) .

Regards,
Christophe.

**Comment by GeorgescuC** [comment]
Thanks to @chent5 sharing their data, the issue is now fixed in https://github.com/broadinstitute/infercnv/commit/fbc5e04f6ab5ebe4559028b7afa5b9ada09289da . The error was due to one of the contigs only having 1 gene left on it and that not being a handled case when defining the column widths of the heatmap for plot_chr_scale=T. Such contigs that are not part of the primary assembly should however most likely be removed from the analysis using the "chr_exclude" option when creating the infercnv object as no smoothing is possible and a single isolated gene is too noisy for meaningful analysis.

**Comment by chent5** [comment]
It works now. Thank you so much!
