### ISSUE TITLE
Add ground truth CNV from bulk tumor for subcluster mode

### ISSUE THREAD

**Issue by bwang1324** [broadinstitute/infercnv#480]
Hello, 

Thank you for distributing and maintaining this tool. I have CNV calls from matched bulk WES and 10X multiome scRNA (based on infercnv). I would like to use the bulk CNV as "ground truth" to identify subclusters in scRNA data (which deviate from this bulk CNV). Could you please provide suggestions on how to do so, ie in terms of which scripts to alter etc? Thank you.

Best,
Boya

**Comment by GeorgescuC** [comment]
Hi @bwang1324 ,

One thing I have done in the past to compare WES results to infercnv results is to manually add the WES results as fake clonal cells (clonal so they are tall enough to be visible) in postprocessing and plot the figures again.

I am attaching [a script prepare_fake_rows_from_wes.R](https://github.com/broadinstitute/infercnv/files/10108588/prepare_fake_rows_from_wes.R.txt) I have used in the past that you can use as a base for this, but you will need to tweak it to read and scale your WES data.

You can otherwise calculate a score for how well the CNVs identified by infercnv match with those of you WES data based on intervals. If you prefer this option, I can also share some scripts I have wrote to do that for benchmarking, but they will likely need some editing to fit your needs.

Regards,
Christophe.

**Comment by bwang1324** [comment]
Dear Christophe, Thank you for your response this is very help!
