### ISSUE TITLE
Detect the CNV in a specific chromosome

### ISSUE THREAD

**Issue by muntajihad** [broadinstitute/infercnv#486]
Hi there,
Thanks you for the nice tool.

I am wondering if it is possible to detect CNV in a specific chromosome? like along choromosome 1 only.

Many thanks

**Comment by frac2738** [comment]
You can specify the chromosome to exclude when you create the inferCNV object: 
`CreateInfercnvObject(... ,chr_exclude = c("chrX", "chrY", "chrM"), ...)` 

In you case, you need to list all the chromosome but the first. 
`chr_exclude = c("chrX", "chrY", "chrM","chr2","chr3", ...)`

**Comment by GeorgescuC** [comment]
Hi @muntajihad ,

As @frac2738 said, you can use the `chr_exclude` option to remove any chromosomes you do not want from the analysis. To exclude all but one chromosome, if you already created the object without excluding them, you can get the list of present chromosomes by running `all_chrs = levels(infercnv_obj@gene_order$chr)`, then remove from the list the one chromosome you want to keep, and send that list as the argument when creating the new object. Otherwise a `unique()` call on the column of the gene order input with the list of chromosomes will produce a similar list.

One thing to keep in mind if you end up removing all but one chromosome is that the clonality of your cells will likely look much simpler than it actually is if you looked at all chromosomes.

Regards,
Christophe.
