### ISSUE TITLE
Gene count influencing CNV detection

### ISSUE THREAD

**Issue by andynkili** [broadinstitute/infercnv#517]
Dear inferCNV support team,

I am wondering how the number of genes expressed may influence the CNV detection.
Indeed, as [Gulati et al](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7694873/) have noted that progenitor cell tend to have higher gene count, I am afraid to miss some CNV in the same lineage on more differentiated cells.
For example, on my dataset, I can see than progenitor cells express more genes (as expected) and have (way) more CNVs than differentiated cells (expressing less genes) from the same cell type.
So is it possible that CNVs harbored by differentiated cells are missed by inferCNV?

Best,
Andy

**Comment by GeorgescuC** [comment]
Hi @andynkili ,

In short, yes, due to limitations of RNA vs DNA.
There are 2 main factors that can affect CNV detection in this regard. First, because this is RNAseq, it is not possible to identify any CNVs that cover non expressed stretches of genes if they are not surrounded by expressed genes part of the same CNV, simply because we would have no reads to support it in either normal or malignant cells. If there are enough expressed genes in a CNV region, then we can identify the region between the first and last expressed genes that are part of it, although we might still miss some non expressed genes on the outer boundaries.
Depending on how many genes you have, the gene density you will vary. Because we smooth the expression over a window of genes, the lower the gene density, the further away neighbor genes tend to be from each other, so the harder it becomes to identify the smaller CNVs, and the more "bleeding" between regions could happen. There is an option to set the smoothing window size by base pairs instead of absolute number of genes to reduce potential bleeding, but there are regions where there will be too few genes for proper smoothing (especially around the centromere) so the results in those regions will be very noisy.

Regards,
Christophe.

**Comment by andynkili** [comment]
It all make sense. Thank you so much for your insight on this matter.

Best,
Andy
