### ISSUE TITLE
docker image 

### ISSUE THREAD

**Issue by mea2712** [broadinstitute/infercnv#544]
I'm trying to build an image in a mac M1. When I upload it to a CentOS server it fails.

My docker file looks like:

`
FROM trinityctat/infercnv:1.16.0-multiarch

RUN R -e 'install.packages("remotes")'
RUN R -e 'install.packages("BiocManager")'

RUN R -e 'BiocManager::install("rtracklayer")'
`

I execute it as:
`docker image build -f $PWD/Dockerfile -t trinityctat_infercnv:1.16.0 --platform amd64 .`
`docker save edb595b6ea31 -o trinityctat-infercnv.1.16.0.tar`

Upload to server and:
`singularity build trinityctat-infercnv.1.16.0.sif docker-archive://infercnv.1.16.0.tar`

It builds ok, but when trying to test it:
`singularity shell trinityctat-infercnv.1.16.0.sif`

I get the error:
`FATAL: could not open image trinityctat.1.16.0.sif: the image's architecture (arm64) could not run on the host 's (amd64)`

This has not happened when building other images. I also tried `FROM trinityctat/infercnv:1.16.0` in the dockerfile but it didn't help
Do you have any tips or ideas as to how to proceed?
Thanks!

**Comment by GeorgescuC** [comment]
Hi @mea2712 ,

I have been actively updating the Docker images today specifically because the multi architecture build does not seem to be working properly in all cases. I finished rebuilding the image `trinityctat/infercnv:1.16.0-multiarch` your are using as source on a different machine around the same time you posted and this one seems to be working better (at least for amd64) because the Terra workflow that uses it can finally find and run it.

To test the new version of the image, try pulling/building your Docker image again with the `--pull --no-cache` arguments to make sure the latest version is used rather than an older cached one.

The amd64 version of the image should have the sha256: `56d3725d30a68f93a78b56b8c8b183bcd8d9aecea8d8fcdcd239337b30b49b4c`.

Regards,
Christophe.

**Comment by mea2712** [comment]
@GeorgescuC 
It seems to be working now. Thanks!
