### ISSUE TITLE
STEP 18 running more than 18 hours and not forward to the next steps

### ISSUE THREAD

**Issue by 42kuroniko** [broadinstitute/infercnv#557]
This is my codes,
```
 infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1, 
                             out_dir='.', 
                             cluster_by_groups=T,
                             denoise=TRUE,
                             HMM=TRUE) 
```

and step 18 is stucking here for like 18 hours now, my computer is a 6 Cores and 32GB RAM PC, is this normal or something getting wrong?
```
STEP 18: Run Bayesian Network Model on HMM predicted CNVs

INFO [2023-06-08 19:31:10] Creating the following Directory:  ./BayesNetOutput.HMMi6.leiden.hmm_mode-subclusters
INFO [2023-06-08 19:31:10] Initializing new MCM InferCNV Object.
INFO [2023-06-08 19:31:10] validating infercnv_obj
INFO [2023-06-08 19:31:24] Total CNV's:  129066
INFO [2023-06-08 19:31:24] Loading BUGS Model.
INFO [2023-06-08 20:19:08] Running Sampling Using Parallel with  4 Cores
```

**Comment by GeorgescuC** [comment]
Hi @42kuroniko ,

Step 18 is to run the Bayesian network, which is rather computationally expensive to begin with, but based on the log there are way to many candidate CNV regions identified that need to be processed. This is almost certainly an issue due to the Leiden clustering being overly fragmented, so if you are using the latest version of infercnv, I would recommend looking at the subclutering plot generated before running the HMM and if this is indeed the issue, you can stop the current run. You will most likely need to adjust the `leiden_resolution` parameter down and rerun the subclustering (step 15, the process should pick back up from step 14 on its own) to find a good resolution and improve subclustering. There is now [a video tutorial](https://github.com/broadinstitute/inferCNV/wiki/Running-InferCNV#infercnv-video-tutorial) available that shows an example of how to do that.

Regards,
Christophe.

**Comment by 42kuroniko** [comment]
> 

Thank you!
