### ISSUE TITLE
moving median instead of moving average?

### ISSUE THREAD

**Issue by plijnzaad** [broadinstitute/infercnv#73]
Dear all, 

I wondered if it was easy to implement the use of a moving median, rather than a moving average, to smooth the data? It would seem to be more robust.  Our data seems to have too little coverage and is therefore more noisy, so I would be interested in trying this out. 

It may well be that you already tried this, and that it just doesn't work for some reason, that would also be good to know of course.  

Many thanks,

Philip

**Comment by GeorgescuC** [comment]
Dear @plijnzaad ,

Implementing the use of a moving median for the smoothing you are referring to should be rather easy, but we have not tested it at this step and the window size will most likely need to be adjusted. One thing to note is that the moving average we are using at this time is weighted so that genes further away from the current position weight less (the weights distribution can be associated to a triangle), which may not be the best when using medians.

However, [on one of our development branches](https://github.com/broadinstitute/inferCNV/tree/noise_filtering), we have a method to apply median filtering that we can run on the final inferncv object before plotting, which does reduce noise significantly. It takes the median across both genes and cells (within the limit of cells that cluster together) in a small window (seem to work best with a size within the [5;11] range). In theory you could run that filtering at earlier steps in the processing, but we have not tested it for that use.

Best,
Christophe.

**Comment by plijnzaad** [comment]
Thanks for you quick reply! I will try and have a look at it. Cheers,

Philip

Op wo 6 feb. 2019 om 17:47 schreef GeorgescuC <notifications@github.com>:
